const CryptoViewerIconsMap: Record<string, { unicode: string }> = {
  coin: { unicode: '\uE800' },
  coins: { unicode: '\uE801' },
  star_empty: { unicode: '\uE802' },
  star: { unicode: '\uE803' },
  wallet: { unicode: '\uE804' },
  prices: { unicode: '\uE805' },
  next: { unicode: '\uE806' },
  back: { unicode: '\uE807' },
  low: { unicode: '\uE808' },
  high: { unicode: '\uE809' },
  volume: { unicode: '\uE80A' },
  plus: { unicode: '\uE80B' },
  minus: { unicode: '\uE80C' },
  settings: { unicode: '\uE80D' },
  link: { unicode: '\uE80E' },
  link_alt: { unicode: '\uE80F' },
  home: { unicode: '\uE810' },
  user: { unicode: '\uE811' },
  bell_active: { unicode: '\uE812' },
  bell: { unicode: '\uE813' },
  donate: { unicode: '\uE814' },
};

export default CryptoViewerIconsMap;
