/* eslint-disable global-require */
const CryptoCurrenciesIconMap: Record<string, {
  icon: any,
  color: string,
  description: string,
  website: string,
}> = {
  $pac: {
    icon: require('cryptocurrency-icons/128/color/$pac.png'),
    color: '#F5EB17',
    description: '',
    website: '',
  },
  '0xbtc': {
    icon: require('cryptocurrency-icons/128/color/0xbtc.png'),
    color: '#FF914C',
    description: '',
    website: '',
  },
  '1inch': {
    icon: require('../../assets/cryptos/1inch.png'),
    color: '#1B314F',
    description: '1INCH is an Ethereum token that powers 1inch, a decentralized exchange that aims to offer the “best rates by discovering the most efficient swapping routes across all leading DEXes.” Decentralized exchanges (a.k.a. DEXes) like 1inch enable users to transact tokens without an intermediary. 1inch aggregates token prices across decentralized exchanges in order to find the best prices for users.',
    website: 'https://1inch.exchange/',
  },
  '2give': {
    icon: require('cryptocurrency-icons/128/color/2give.png'),
    color: '#F1CB60',
    description: '',
    website: '',
  },
  aave: {
    icon: require('../../assets/cryptos/aave.png'),
    color: '#B6509E',
    description: 'Aave (AAVE) is an Ethereum token that powers Aave, a decentralized non-custodial money market protocol where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow cryptocurrencies in exchange for paying a variable interest rate.',
    website: 'https://aave.com/',
  },
  abt: {
    icon: require('cryptocurrency-icons/128/color/abt.png'),
    color: '#3EFEFF',
    description: '',
    website: '',
  },
  ach: {
    icon: require('../../assets/cryptos/ach.png'),
    color: '#2E3567',
    description: 'ACH is an Ethereum token that powers Alchemy Pay, a platform that enables payments using a wide variety of fiat and cryptocurrencies. Fees are paid using the ACH token and users can earn ACH rewards for purchases.',
    website: 'https://www.alchemytech.io/',
  },
  act: {
    icon: require('cryptocurrency-icons/128/color/act.png'),
    color: '#767DFF',
    description: '',
    website: '',
  },
  actn: {
    icon: require('cryptocurrency-icons/128/color/actn.png'),
    color: '#FF0000',
    description: '',
    website: '',
  },
  ada: {
    icon: require('cryptocurrency-icons/128/color/ada.png'),
    color: '#0D1E30',
    description: 'Cardano (ADA) is a blockchain platform built on a proof-of-stake consensus protocol (called Ouroboros) that validates transactions without high energy costs. Development on Cardano uses the Haskell programming language, which is described as enabling Cardano “to pursue evidence-based development for unparalleled security and stability.” The blockchain’s native token, ADA, is named after the 19th century mathematician, Ada Lovelace.',
    website: 'https://cardano.org/',
  },
  add: {
    icon: require('cryptocurrency-icons/128/color/add.png'),
    color: '#FEC807',
    description: '',
    website: '',
  },
  adx: {
    icon: require('cryptocurrency-icons/128/color/adx.png'),
    color: '#1B75BC',
    description: '',
    website: '',
  },
  ae: {
    icon: require('cryptocurrency-icons/128/color/ae.png'),
    color: '#DE3F6B',
    description: '',
    website: '',
  },
  aeon: {
    icon: require('cryptocurrency-icons/128/color/aeon.png'),
    color: '#134451',
    description: '',
    website: '',
  },
  aeur: {
    icon: require('cryptocurrency-icons/128/color/aeur.png'),
    color: '#051D2D',
    description: '',
    website: '',
  },
  agi: {
    icon: require('cryptocurrency-icons/128/color/agi.png'),
    color: '#6916FF',
    description: '',
    website: '',
  },
  agrs: {
    icon: require('cryptocurrency-icons/128/color/agrs.png'),
    color: '#F49E00',
    description: '',
    website: '',
  },
  aion: {
    icon: require('cryptocurrency-icons/128/color/aion.png'),
    color: '#00BFEC',
    description: '',
    website: '',
  },
  algo: {
    icon: require('cryptocurrency-icons/128/color/algo.png'),
    color: '#000000',
    description: 'Algorand is a cryptocurrency and blockchain protocol that aims to be simultaneously scalable, secure, and decentralized. It uses a consensus algorithm called pure proof-of-stake.',
    website: 'https://www.algorand.com/',
  },
  amb: {
    icon: require('cryptocurrency-icons/128/color/amb.png'),
    color: '#3D5BE1',
    description: '',
    website: '',
  },
  amp: {
    icon: require('../../assets/cryptos/amp.png'),
    color: '#E42E95',
    description: 'Amp is an Ethereum token that aims to “collateralize payments on the Flexa Network, making them instant and secure.” If a BTC or ETH payment fails due to unconfirmed or long transaction times “the Amp collateral can instead be liquidated to cover losses” while the vendor receives payment in fiat, potentially providing greater assurances to both parties.',
    website: 'https://amptoken.org/',
  },
  ampl: {
    icon: require('cryptocurrency-icons/128/color/ampl.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  ankr: {
    icon: require('../../assets/cryptos/ankr.png'),
    color: '#579BF0',
    description: 'Ankr (ANKR) is an Ethereum token that powers Ankr, a distributed computing platform that aims to make it easy and affordable for developers to deploy and use a variety of blockchains. The ANKR token can be used to pay for services on Ankr, such as node deployment, and also acts as an incentive for network participants.',
    website: 'https://www.ankr.com/',
  },
  ant: {
    icon: require('cryptocurrency-icons/128/color/ant.png'),
    color: '#2CD3E1',
    description: '',
    website: '',
  },
  apex: {
    icon: require('cryptocurrency-icons/128/color/apex.png'),
    color: '#1F4C9F',
    description: '',
    website: '',
  },
  appc: {
    icon: require('cryptocurrency-icons/128/color/appc.png'),
    color: '#FD875E',
    description: '',
    website: '',
  },
  ardr: {
    icon: require('cryptocurrency-icons/128/color/ardr.png'),
    color: '#3C87C7',
    description: '',
    website: '',
  },
  arg: {
    icon: require('cryptocurrency-icons/128/color/arg.png'),
    color: '#A71435',
    description: '',
    website: '',
  },
  ark: {
    icon: require('cryptocurrency-icons/128/color/ark.png'),
    color: '#F70000',
    description: '',
    website: '',
  },
  arn: {
    icon: require('cryptocurrency-icons/128/color/arn.png'),
    color: '#0092B5',
    description: '',
    website: '',
  },
  arnx: {
    icon: require('cryptocurrency-icons/128/color/arnx.png'),
    color: '#436697',
    description: '',
    website: '',
  },
  ary: {
    icon: require('cryptocurrency-icons/128/color/ary.png'),
    color: '#343434',
    description: '',
    website: '',
  },
  ast: {
    icon: require('cryptocurrency-icons/128/color/ast.png'),
    color: '#0061FF',
    description: '',
    website: '',
  },
  atm: {
    icon: require('cryptocurrency-icons/128/color/atm.png'),
    color: '#346FCD',
    description: '',
    website: '',
  },
  atom: {
    icon: require('cryptocurrency-icons/128/color/atom.png'),
    color: '#2F3148',
    description: 'Cosmos (ATOM) is a cryptocurrency that powers an ecosystem of blockchains designed to scale and interoperate with each other. The team aims to "create an Internet of Blockchains, a network of blockchains able to communicate with each other in a decentralized way." Cosmos is a proof-of-stake chain. ATOM holders can stake their tokens in order to maintain the network and receive more ATOM as a reward.',
    website: 'https://cosmos.network/',
  },
  audr: {
    icon: require('cryptocurrency-icons/128/color/audr.png'),
    color: '#34318A',
    description: '',
    website: '',
  },
  auto: {
    icon: require('cryptocurrency-icons/128/color/auto.png'),
    color: '#FAB431',
    description: '',
    website: '',
  },
  axs: {
    icon: require('../../assets/cryptos/axs.png'),
    color: '#0055D5',
    description: 'AXS is an Ethereum token that powers Axie Infinity, a blockchain-based game where players can battle, collect, and build a digital kingdom for their pets. AXS holders can claim rewards for staking their tokens, playing the game, and participating in key governance votes.',
    website: 'https://axieinfinity.com/',
  },
  aywa: {
    icon: require('cryptocurrency-icons/128/color/aywa.png'),
    color: '#3355B5',
    description: '',
    website: '',
  },
  bab: {
    icon: require('cryptocurrency-icons/128/color/bab.png'),
    color: '#F1A013',
    description: '',
    website: '',
  },
  bal: {
    icon: require('cryptocurrency-icons/128/color/bal.png'),
    color: '#1E1E1E',
    description: 'Balancer (BAL) is an Ethereum token that powers the Balancer protocol, an automated market maker that lets anyone create or add liquidity to trading pools while earning customizable trading fees. Balancer pools can have up to 8 tokens and each token can be individually weighted within the pool, such that one token can make up as little as 2% of the total.',
    website: 'https://balancer.finance/',
  },
  band: {
    icon: require('cryptocurrency-icons/128/color/band.png'),
    color: '#516BFF',
    description: 'Band is a cryptocurrency that describes itself as “a cross-chain data oracle platform that aggregates and connects real-world data and APIs to smart contracts.” Band allows blockchains to access data, such as stock prices and weather, that are available via API. Note: Coinbase only supports the Band token running on Ethereum (ERC-20).',
    website: 'https://bandprotocol.com/',
  },
  bat: {
    icon: require('cryptocurrency-icons/128/color/bat.png'),
    color: '#FF5000',
    description: 'BAT is an Ethereum token that powers Brave Software\'s blockchain-based digital advertising platform. Internet users who browse the web using Brave\'s free web browser (available at Brave.com) can choose to replace the ads they see with ads on Brave\'s ad network. Users then receive BAT from advertisers as compensation for their attention.',
    website: 'https://basicattentiontoken.org/',
  },
  bay: {
    icon: require('cryptocurrency-icons/128/color/bay.png'),
    color: '#6356AB',
    description: '',
    website: '',
  },
  bcbc: {
    icon: require('cryptocurrency-icons/128/color/bcbc.png'),
    color: '#004AB5',
    description: '',
    website: '',
  },
  bcc: {
    icon: require('cryptocurrency-icons/128/color/bcc.png'),
    color: '#F7931C',
    description: '',
    website: '',
  },
  bcd: {
    icon: require('cryptocurrency-icons/128/color/bcd.png'),
    color: '#FCC339',
    description: '',
    website: '',
  },
  bch: {
    icon: require('cryptocurrency-icons/128/color/bch.png'),
    color: '#8DC351',
    description: 'Bitcoin Cash is a fork of Bitcoin that seeks to add more transaction capacity to the network in order to be useful for everyday transactions.',
    website: 'http://bch.info/',
  },
  bcio: {
    icon: require('cryptocurrency-icons/128/color/bcio.png'),
    color: '#3F43AD',
    description: '',
    website: '',
  },
  bcn: {
    icon: require('cryptocurrency-icons/128/color/bcn.png'),
    color: '#F04086',
    description: '',
    website: '',
  },
  bco: {
    icon: require('cryptocurrency-icons/128/color/bco.png'),
    color: '#2C76B7',
    description: '',
    website: '',
  },
  bcpt: {
    icon: require('cryptocurrency-icons/128/color/bcpt.png'),
    color: '#404040',
    description: '',
    website: '',
  },
  bdl: {
    icon: require('cryptocurrency-icons/128/color/bdl.png'),
    color: '#E54C40',
    description: '',
    website: '',
  },
  beam: {
    icon: require('cryptocurrency-icons/128/color/beam.png'),
    color: '#0B76FF',
    description: '',
    website: '',
  },
  bela: {
    icon: require('cryptocurrency-icons/128/color/bela.png'),
    color: '#13A0F6',
    description: '',
    website: '',
  },
  bix: {
    icon: require('cryptocurrency-icons/128/color/bix.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  blcn: {
    icon: require('cryptocurrency-icons/128/color/blcn.png'),
    color: '#2AABE4',
    description: '',
    website: '',
  },
  blk: {
    icon: require('cryptocurrency-icons/128/color/blk.png'),
    color: '#181818',
    description: '',
    website: '',
  },
  block: {
    icon: require('cryptocurrency-icons/128/color/block.png'),
    color: '#101341',
    description: '',
    website: '',
  },
  blz: {
    icon: require('cryptocurrency-icons/128/color/blz.png'),
    color: '#18578C',
    description: '',
    website: '',
  },
  bnb: {
    icon: require('cryptocurrency-icons/128/color/bnb.png'),
    color: '#F3BA2F',
    description: '',
    website: '',
  },
  bnt: {
    icon: require('cryptocurrency-icons/128/color/bnt.png'),
    color: '#000E2B',
    description: 'Bancor Network Token (BNT) is an Ethereum token that powers the Bancor protocol. The protocol describes itself as “a fully on-chain liquidity protocol that can be implemented on any smart contract-enabled blockchain.”',
    website: 'https://bancor.network/',
  },
  bnty: {
    icon: require('cryptocurrency-icons/128/color/bnty.png'),
    color: '#FD7A3D',
    description: '',
    website: '',
  },
  bond: {
    icon: require('../../assets/cryptos/bond.png'),
    color: '#FF4339',
    description: 'BOND is an Ethereum token that governs BarnBridge, a protocol that enables users to hedge against DeFi yield sensitivity and price volatility. Its first application, SMART Yield, allows users to choose between risk profiles for lending on DeFi protocols such as Aave and Compound. By using SMART Yield, senior bond investors can receive fixed rates at potentially lower risk while junior bond investors can receive higher rates at higher risk.',
    website: 'https://barnbridge.com/',
  },
  booty: {
    icon: require('cryptocurrency-icons/128/color/booty.png'),
    color: '#00B4F4',
    description: '',
    website: '',
  },
  bos: {
    icon: require('cryptocurrency-icons/128/color/bos.png'),
    color: '#00A8D6',
    description: '',
    website: '',
  },
  bpt: {
    icon: require('cryptocurrency-icons/128/color/bpt.png'),
    color: '#0F63D8',
    description: '',
    website: '',
  },
  bq: {
    icon: require('cryptocurrency-icons/128/color/bq.png'),
    color: '#1D1D1D',
    description: '',
    website: '',
  },
  brd: {
    icon: require('cryptocurrency-icons/128/color/brd.png'),
    color: '#FE5D86',
    description: '',
    website: '',
  },
  bsd: {
    icon: require('cryptocurrency-icons/128/color/bsd.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  bsv: {
    icon: require('cryptocurrency-icons/128/color/bsv.png'),
    color: '#EAB304',
    description: '',
    website: '',
  },
  btc: {
    icon: require('cryptocurrency-icons/128/color/btc.png'),
    color: '#F7931B',
    description: 'The world’s first cryptocurrency, Bitcoin is stored and exchanged securely on the internet through a digital ledger known as a blockchain. Bitcoins are divisible into smaller units known as satoshis — each satoshi is worth 0.00000001 bitcoin.',
    website: 'https://bitcoin.org/',
  },
  btcd: {
    icon: require('cryptocurrency-icons/128/color/btcd.png'),
    color: '#FF6600',
    description: '',
    website: '',
  },
  btch: {
    icon: require('cryptocurrency-icons/128/color/btch.png'),
    color: '#4700C2',
    description: '',
    website: '',
  },
  btcp: {
    icon: require('cryptocurrency-icons/128/color/btcp.png'),
    color: '#272D63',
    description: '',
    website: '',
  },
  btcz: {
    icon: require('cryptocurrency-icons/128/color/btcz.png'),
    color: '#F8C24A',
    description: '',
    website: '',
  },
  btdx: {
    icon: require('cryptocurrency-icons/128/color/btdx.png'),
    color: '#00AAFF',
    description: '',
    website: '',
  },
  btg: {
    icon: require('cryptocurrency-icons/128/color/btg.png'),
    color: '#EBA809',
    description: '',
    website: '',
  },
  btm: {
    icon: require('cryptocurrency-icons/128/color/btm.png'),
    color: '#504C4C',
    description: '',
    website: '',
  },
  bts: {
    icon: require('cryptocurrency-icons/128/color/bts.png'),
    color: '#35BAEB',
    description: '',
    website: '',
  },
  btt: {
    icon: require('cryptocurrency-icons/128/color/btt.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  btx: {
    icon: require('cryptocurrency-icons/128/color/btx.png'),
    color: '#ED309C',
    description: '',
    website: '',
  },
  burst: {
    icon: require('cryptocurrency-icons/128/color/burst.png'),
    color: '#2D2D2D',
    description: '',
    website: '',
  },
  bze: {
    icon: require('cryptocurrency-icons/128/color/bze.png'),
    color: '#00AEEF',
    description: '',
    website: '',
  },
  call: {
    icon: require('cryptocurrency-icons/128/color/call.png'),
    color: '#FCB414',
    description: '',
    website: '',
  },
  cc: {
    icon: require('cryptocurrency-icons/128/color/cc.png'),
    color: '#36B0F3',
    description: '',
    website: '',
  },
  cdn: {
    icon: require('cryptocurrency-icons/128/color/cdn.png'),
    color: '#F70808',
    description: '',
    website: '',
  },
  cdt: {
    icon: require('cryptocurrency-icons/128/color/cdt.png'),
    color: '#272731',
    description: '',
    website: '',
  },
  cenz: {
    icon: require('cryptocurrency-icons/128/color/cenz.png'),
    color: '#3088F2',
    description: '',
    website: '',
  },
  cgld: {
    icon: require('../../assets/cryptos/cgld.png'),
    color: '#FBCC5C',
    description: 'Celo is the core utility, reserve, staking, and governance asset for the Celo platform. The platform aims to make financial tools borderless, easy to use, and accessible for anyone with a mobile phone.',
    website: 'https://celo.org/',
  },
  chain: {
    icon: require('cryptocurrency-icons/128/color/chain.png'),
    color: '#00ACED',
    description: '',
    website: '',
  },
  chat: {
    icon: require('cryptocurrency-icons/128/color/chat.png'),
    color: '#1C98F7',
    description: '',
    website: '',
  },
  chips: {
    icon: require('cryptocurrency-icons/128/color/chips.png'),
    color: '#598182',
    description: '',
    website: '',
  },
  chz: {
    icon: require('../../assets/cryptos/chz.png'),
    color: '#B02728',
    description: 'Chiliz (CHZ) is an Ethereum token that powers Socios.com, a platform that lets users trade tokens to show their support for professional sports teams. The tokens on Socios.com — called Fan Tokens — make users eligible for rewards and promotions and can also be used to influence team decisions by popular voting on the Chiliz blockchain.',
    website: 'https://www.chiliz.com/',
  },
  cix: {
    icon: require('cryptocurrency-icons/128/color/cix.png'),
    color: '#0576B4',
    description: '',
    website: '',
  },
  clam: {
    icon: require('cryptocurrency-icons/128/color/clam.png'),
    color: '#20C5D3',
    description: '',
    website: '',
  },
  cloak: {
    icon: require('cryptocurrency-icons/128/color/cloak.png'),
    color: '#FF3A00',
    description: '',
    website: '',
  },
  clv: {
    icon: require('../../assets/cryptos/clv.png'),
    color: '#42C37B',
    description: 'Clover Finance is a blockchain infrastructure platform that’s focused on cross-chain compatibility for DeFi applications. The CLV token is used to pay for Clover transactions and to vote for network upgrades. Clover also aims to enable interoperability between Bitcoin and other blockchains. Note: Coinbase currently supports CLV running on Ethereum (ERC-20).',
    website: 'https://clover.finance/',
  },
  cmm: {
    icon: require('cryptocurrency-icons/128/color/cmm.png'),
    color: '#2FD2E5',
    description: '',
    website: '',
  },
  cmt: {
    icon: require('cryptocurrency-icons/128/color/cmt.png'),
    color: '#C1A05C',
    description: '',
    website: '',
  },
  cnd: {
    icon: require('cryptocurrency-icons/128/color/cnd.png'),
    color: '#383939',
    description: '',
    website: '',
  },
  cnx: {
    icon: require('cryptocurrency-icons/128/color/cnx.png'),
    color: '#4C6BAE',
    description: '',
    website: '',
  },
  cny: {
    icon: require('cryptocurrency-icons/128/color/cny.png'),
    color: '#FF4315',
    description: '',
    website: '',
  },
  cob: {
    icon: require('cryptocurrency-icons/128/color/cob.png'),
    color: '#13BF99',
    description: '',
    website: '',
  },
  colx: {
    icon: require('cryptocurrency-icons/128/color/colx.png'),
    color: '#77C3B0',
    description: '',
    website: '',
  },
  comp: {
    icon: require('cryptocurrency-icons/128/color/comp.png'),
    color: '#01D396',
    description: 'Compound (COMP) is an Ethereum token that enables community governance of the Compound protocol. The protocol is a series of decentralized interest rate markets that allow users to supply and borrow Ethereum tokens at variable interest rates. COMP token holders and their delegates can also debate, propose, and vote on changes to the protocol.',
    website: 'https://compound.finance/',
  },
  coqui: {
    icon: require('cryptocurrency-icons/128/color/coqui.png'),
    color: '#71C800',
    description: '',
    website: '',
  },
  coti: {
    icon: require('../../assets/cryptos/coti.png'),
    color: '#229FD0',
    description: 'COTI is a token that powers Coti, a project that describes itself as a “DAG (directed acyclic graph) protocol optimized for creating decentralized payment networks and stable coins.” Coti uses Trustchain, a decentralized ledger that can process over 100,000 transactions per second, to power online and offline payments, loyalty payments, stablecoins, and more. Note: Coinbase currently only supports COTI running on the Ethereum blockchain (ERC-20).',
    website: 'https://coti.io/',
  },
  cred: {
    icon: require('cryptocurrency-icons/128/color/cred.png'),
    color: '#37E8A3',
    description: '',
    website: '',
  },
  crpt: {
    icon: require('cryptocurrency-icons/128/color/crpt.png'),
    color: '#189AA5',
    description: '',
    website: '',
  },
  crv: {
    icon: require('../../assets/cryptos/crv.png'),
    color: '#721BFF',
    description: 'Curve (CRV) is an Ethereum token that powers Curve.fi, a decentralized exchange and automated market maker protocol. The protocol is designed to make it easy to swap between similar ERC-20 tokens, primarily stablecoins (like USDC and DAI) and Ethereum-based Bitcoin tokens (like WBTC and renBTC). In order to minimize impermanent loss, the protocol only hosts pools of similar assets. This means you can provide USDC-DAI-USDT liquidity on Curve, but not, for example, USDC-WBTC. The CRV token can be locked for various periods of time (up to 4 years) in order to vote on governance and claim protocol fees as a reward.',
    website: 'https://resources.curve.fi/',
  },
  crw: {
    icon: require('cryptocurrency-icons/128/color/crw.png'),
    color: '#0F1529',
    description: '',
    website: '',
  },
  cs: {
    icon: require('cryptocurrency-icons/128/color/cs.png'),
    color: '#262626',
    description: '',
    website: '',
  },
  ctr: {
    icon: require('cryptocurrency-icons/128/color/ctr.png'),
    color: '#FDDE6C',
    description: '',
    website: '',
  },
  ctsi: {
    icon: require('../../assets/cryptos/ctsi.png'),
    color: '#1A1B1D',
    description: 'CTSI is a utility token that powers the Cartesi network, which aims to solve blockchain scalability and high fees using a technology called Optimistic Rollups. CTSI can be used for staking and fees for processing data on the network. Notably, Cartesi enables smart contract creation using mainstream programming languages.',
    website: 'https://cartesi.io/',
  },
  ctxc: {
    icon: require('cryptocurrency-icons/128/color/ctxc.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  cvc: {
    icon: require('cryptocurrency-icons/128/color/cvc.png'),
    color: '#3AB03E',
    description: 'Civic (CVC) is an Ethereum token used to power Civic’s identity verification protocol. Users who verify their information through Civic can then securely share both their info and the verification with service providers, reducing the need to constantly re-verify their identity. In return for this convenience, service providers may provide users and verifiers with CVC.',
    website: 'https://www.civic.com/',
  },
  d: {
    icon: require('cryptocurrency-icons/128/color/d.png'),
    color: '#B8B8B8',
    description: '',
    website: '',
  },
  dai: {
    icon: require('cryptocurrency-icons/128/color/dai.png'),
    color: '#F3B732',
    description: 'Dai (DAI) is a decentralized stablecoin running on Ethereum (ETH) that attempts to maintain a value of $1.00 USD. Unlike centralized stablecoins, Dai isn\'t backed by US dollars in a bank account. Instead, it’s backed by collateral on the Maker platform. Note: if the Dai credit system is upgraded or shutdown, Dai holders may need to convert their Dai to Ethereum through the Maker platform. Read more at makerdao.com/whitepaper.',
    website: 'https://www.makerdao.com/',
  },
  dash: {
    icon: require('cryptocurrency-icons/128/color/dash.png'),
    color: '#018CE7',
    description: 'Dash is a cryptocurrency with optional speed and privacy features. Its unique network architecture consists of both regular miners and privileged machines called Masternodes.',
    website: 'https://www.dash.org/',
  },
  dat: {
    icon: require('cryptocurrency-icons/128/color/dat.png'),
    color: '#2D9CDB',
    description: '',
    website: '',
  },
  data: {
    icon: require('cryptocurrency-icons/128/color/data.png'),
    color: '#E9570F',
    description: '',
    website: '',
  },
  dbc: {
    icon: require('cryptocurrency-icons/128/color/dbc.png'),
    color: '#5BC1D4',
    description: '',
    website: '',
  },
  dcn: {
    icon: require('cryptocurrency-icons/128/color/dcn.png'),
    color: '#136485',
    description: '',
    website: '',
  },
  dcr: {
    icon: require('cryptocurrency-icons/128/color/dcr.png'),
    color: '#2ED6A1',
    description: '',
    website: '',
  },
  deez: {
    icon: require('cryptocurrency-icons/128/color/deez.png'),
    color: '#939393',
    description: '',
    website: '',
  },
  dent: {
    icon: require('cryptocurrency-icons/128/color/dent.png'),
    color: '#666666',
    description: '',
    website: '',
  },
  dew: {
    icon: require('cryptocurrency-icons/128/color/dew.png'),
    color: '#FEC907',
    description: '',
    website: '',
  },
  dgb: {
    icon: require('cryptocurrency-icons/128/color/dgb.png'),
    color: '#006AD2',
    description: '',
    website: '',
  },
  dgd: {
    icon: require('cryptocurrency-icons/128/color/dgd.png'),
    color: '#F4D029',
    description: '',
    website: '',
  },
  dlt: {
    icon: require('cryptocurrency-icons/128/color/dlt.png'),
    color: '#F4AE95',
    description: '',
    website: '',
  },
  dnt: {
    icon: require('cryptocurrency-icons/128/color/dnt.png'),
    color: '#2D398F',
    description: 'District0x is an Ethereum token that powers a network of decentralized marketplaces and communities called districts. The token is required for application to the District Registry and is used to signal support or disapproval for proposals made by network participants.',
    website: 'https://district0x.io/',
  },
  dock: {
    icon: require('cryptocurrency-icons/128/color/dock.png'),
    color: '#786DBC',
    description: '',
    website: '',
  },
  doge: {
    icon: require('cryptocurrency-icons/128/color/doge.png'),
    color: '#C4A634',
    description: 'Dogecoin (DOGE) was created in 2013 as a lighthearted alternative to traditional cryptocurrencies like Bitcoin. The Dogecoin name and Shiba Inu logo are based on a meme. Unlike Bitcoin, which is designed to be scarce, Dogecoin is intentionally abundant — 10,000 new coins are mined every minute and there is no maximum supply.',
    website: 'https://dogecoin.com/',
  },
  dot: {
    icon: require('cryptocurrency-icons/128/color/dot.png'),
    color: '#E6007A',
    description: 'Polkadot is a protocol that enables cross-blockchain transfers of any type of data or asset. By uniting multiple blockchains, Polkadot aims to achieve high degrees of security and scalability. DOT serves as the protocol’s governance token and can be used for staking to secure the network or to connect (“bond”) new chains.',
    website: 'https://polkadot.network/',
  },
  drgn: {
    icon: require('cryptocurrency-icons/128/color/drgn.png'),
    color: '#C91111',
    description: '',
    website: '',
  },
  drop: {
    icon: require('cryptocurrency-icons/128/color/drop.png'),
    color: '#242D3D',
    description: '',
    website: '',
  },
  dta: {
    icon: require('cryptocurrency-icons/128/color/dta.png'),
    color: '#74D269',
    description: '',
    website: '',
  },
  dth: {
    icon: require('cryptocurrency-icons/128/color/dth.png'),
    color: '#3C80F1',
    description: '',
    website: '',
  },
  dtr: {
    icon: require('cryptocurrency-icons/128/color/dtr.png'),
    color: '#121747',
    description: '',
    website: '',
  },
  ebst: {
    icon: require('cryptocurrency-icons/128/color/ebst.png'),
    color: '#1693D4',
    description: '',
    website: '',
  },
  eca: {
    icon: require('cryptocurrency-icons/128/color/eca.png'),
    color: '#AA15DD',
    description: '',
    website: '',
  },
  edg: {
    icon: require('cryptocurrency-icons/128/color/edg.png'),
    color: '#2B1544',
    description: '',
    website: '',
  },
  edo: {
    icon: require('cryptocurrency-icons/128/color/edo.png'),
    color: '#242424',
    description: '',
    website: '',
  },
  edoge: {
    icon: require('cryptocurrency-icons/128/color/edoge.png'),
    color: '#0FACF3',
    description: '',
    website: '',
  },
  ela: {
    icon: require('cryptocurrency-icons/128/color/ela.png'),
    color: '#3FBADF',
    description: '',
    website: '',
  },
  elec: {
    icon: require('cryptocurrency-icons/128/color/elec.png'),
    color: '#FF9900',
    description: '',
    website: '',
  },
  elf: {
    icon: require('cryptocurrency-icons/128/color/elf.png'),
    color: '#2B5EBB',
    description: '',
    website: '',
  },
  elix: {
    icon: require('cryptocurrency-icons/128/color/elix.png'),
    color: '#00ADED',
    description: '',
    website: '',
  },
  ella: {
    icon: require('cryptocurrency-icons/128/color/ella.png'),
    color: '#396A28',
    description: '',
    website: '',
  },
  emc: {
    icon: require('cryptocurrency-icons/128/color/emc.png'),
    color: '#B49FFC',
    description: '',
    website: '',
  },
  emc2: {
    icon: require('cryptocurrency-icons/128/color/emc2.png'),
    color: '#00CCFF',
    description: '',
    website: '',
  },
  eng: {
    icon: require('cryptocurrency-icons/128/color/eng.png'),
    color: '#2F2F2F',
    description: '',
    website: '',
  },
  enj: {
    icon: require('cryptocurrency-icons/128/color/enj.png'),
    color: '#614DBE',
    description: 'Enjin Coin (ENJ) is an Ethereum token that aims to “make it easy for individuals, businesses, and brands to use non-fungible tokens (NFTs).” ENJ is used to directly back the value of NFTs minted within the Enjin ecosystem.',
    website: 'https://enjin.io/',
  },
  entrp: {
    icon: require('cryptocurrency-icons/128/color/entrp.png'),
    color: '#FA5836',
    description: '',
    website: '',
  },
  eon: {
    icon: require('cryptocurrency-icons/128/color/eon.png'),
    color: '#443F54',
    description: '',
    website: '',
  },
  eop: {
    icon: require('cryptocurrency-icons/128/color/eop.png'),
    color: '#35A7DF',
    description: '',
    website: '',
  },
  eos: {
    icon: require('cryptocurrency-icons/128/color/eos.png'),
    color: '#000000',
    description: 'EOS is a cryptocurrency designed to support large-scale applications. There are no fees to send or receive EOS. Instead, the protocol rewards the entities that run the network periodically with new EOS, effectively substituting inflation for transaction fees.',
    website: 'https://eos.io/',
  },
  eqli: {
    icon: require('cryptocurrency-icons/128/color/eqli.png'),
    color: '#C9A35E',
    description: '',
    website: '',
  },
  equa: {
    icon: require('cryptocurrency-icons/128/color/equa.png'),
    color: '#F68922',
    description: '',
    website: '',
  },
  etc: {
    icon: require('cryptocurrency-icons/128/color/etc.png'),
    color: '#328432',
    description: 'Ethereum Classic is a cryptocurrency with a special focus on immutability, popularly expressed as “code is law.”',
    website: 'https://ethereumclassic.org/',
  },
  eth: {
    icon: require('cryptocurrency-icons/128/color/eth.png'),
    color: '#627EEB',
    description: 'Ethereum is a decentralized computing platform that uses ETH (also called Ether) to pay transaction fees (or “gas”). Developers can use Ethereum to run decentralized applications (dApps) and issue new crypto assets, known as Ethereum tokens.',
    website: 'https://ethereum.org/',
  },
  ethos: {
    icon: require('cryptocurrency-icons/128/color/ethos.png'),
    color: '#00FFBA',
    description: '',
    website: '',
  },
  etn: {
    icon: require('cryptocurrency-icons/128/color/etn.png'),
    color: '#24BEE2',
    description: '',
    website: '',
  },
  etp: {
    icon: require('cryptocurrency-icons/128/color/etp.png'),
    color: '#00A5FF',
    description: '',
    website: '',
  },
  eur: {
    icon: require('cryptocurrency-icons/128/color/eur.png'),
    color: '#0F8FF8',
    description: '',
    website: '',
  },
  evx: {
    icon: require('cryptocurrency-icons/128/color/evx.png'),
    color: '#044AAC',
    description: '',
    website: '',
  },
  exmo: {
    icon: require('cryptocurrency-icons/128/color/exmo.png'),
    color: '#347FFB',
    description: '',
    website: '',
  },
  exp: {
    icon: require('cryptocurrency-icons/128/color/exp.png'),
    color: '#FFAA5C',
    description: '',
    website: '',
  },
  fair: {
    icon: require('cryptocurrency-icons/128/color/fair.png'),
    color: '#C99705',
    description: '',
    website: '',
  },
  farm: {
    icon: require('../../assets/cryptos/farm.png'),
    color: '#BDE4E3',
    description: 'FARM is an Ethereum token that powers Harvest Finance, a yield optimizer that moves funds around the decentralized finance (DeFi) ecosystem in an effort to generate yields. FARM can be used for staking and yield farming on Harvest Finance.',
    website: 'https://harvest.finance/',
  },
  fct: {
    icon: require('cryptocurrency-icons/128/color/fct.png'),
    color: '#417BA4',
    description: '',
    website: '',
  },
  fet: {
    icon: require('../../assets/cryptos/fet.png'),
    color: '#1D2743',
    description: 'FET is an Ethereum token that powers Fetch.ai, a decentralized machine learning platform for applications such as asset trading, gig economy work, and energy grid optimization. Fetch.ai’s first decentralized finance application helps Uniswap users automate trading according to predefined conditions.',
    website: 'https://fetch.ai/',
  },
  fil: {
    icon: require('cryptocurrency-icons/128/color/fil.png'),
    color: '#42C1CA',
    description: 'Filecoin (FIL) is a cryptocurrency that powers the Filecoin network, a decentralized peer-to-peer file storage network that aims to let anyone store, retrieve, and host digital information. FIL tokens are used as payment for these services and as an economic incentive to ensure files are stored reliably over time.',
    website: 'https://filecoin.io/',
  },
  fjc: {
    icon: require('cryptocurrency-icons/128/color/fjc.png'),
    color: '#00AFEC',
    description: '',
    website: '',
  },
  fldc: {
    icon: require('cryptocurrency-icons/128/color/fldc.png'),
    color: '#C40E09',
    description: '',
    website: '',
  },
  flo: {
    icon: require('cryptocurrency-icons/128/color/flo.png'),
    color: '#2080A2',
    description: '',
    website: '',
  },
  forth: {
    icon: require('../../assets/cryptos/forth.png'),
    color: '#4712B0',
    description: 'FORTH is a cryptocurrency that powers Ampleforth, a protocol that automatically adjusts the supply of its native token, AMPL, in response to demand. FORTH is Ampleforth’s governance token. FORTH holders can vote on proposed changes to the Ampleforth protocol or delegate their votes to representatives who vote on their behalf.',
    website: 'https://www.ampleforth.org/',
  },
  fsn: {
    icon: require('cryptocurrency-icons/128/color/fsn.png'),
    color: '#1D9AD7',
    description: '',
    website: '',
  },
  ftc: {
    icon: require('cryptocurrency-icons/128/color/ftc.png'),
    color: '#27323A',
    description: '',
    website: '',
  },
  fuel: {
    icon: require('cryptocurrency-icons/128/color/fuel.png'),
    color: '#4096D0',
    description: '',
    website: '',
  },
  fun: {
    icon: require('cryptocurrency-icons/128/color/fun.png'),
    color: '#ED1968',
    description: '',
    website: '',
  },
  game: {
    icon: require('cryptocurrency-icons/128/color/game.png'),
    color: '#2D485B',
    description: '',
    website: '',
  },
  gas: {
    icon: require('cryptocurrency-icons/128/color/gas.png'),
    color: '#58BF00',
    description: '',
    website: '',
  },
  gbp: {
    icon: require('cryptocurrency-icons/128/color/gbp.png'),
    color: '#BC3FE0',
    description: '',
    website: '',
  },
  gbx: {
    icon: require('cryptocurrency-icons/128/color/gbx.png'),
    color: '#1666AF',
    description: '',
    website: '',
  },
  gbyte: {
    icon: require('cryptocurrency-icons/128/color/gbyte.png'),
    color: '#302C2C',
    description: '',
    website: '',
  },
  generic: {
    icon: require('cryptocurrency-icons/128/color/generic.png'),
    color: '#EFB914',
    description: '',
    website: '',
  },
  gin: {
    icon: require('cryptocurrency-icons/128/color/gin.png'),
    color: '#008DDE',
    description: '',
    website: '',
  },
  glxt: {
    icon: require('cryptocurrency-icons/128/color/glxt.png'),
    color: '#005396',
    description: '',
    website: '',
  },
  gmr: {
    icon: require('cryptocurrency-icons/128/color/gmr.png'),
    color: '#372D2C',
    description: '',
    website: '',
  },
  gno: {
    icon: require('cryptocurrency-icons/128/color/gno.png'),
    color: '#00A6C4',
    description: '',
    website: '',
  },
  gnt: {
    icon: require('cryptocurrency-icons/128/color/gnt.png'),
    color: '#001D57',
    description: 'Golem is an Ethereum token that allows users to pay or receive payment for resources via the Golem protocol. The protocol aims to allow participants in the network to loan out their computer’s spare processing power to others.',
    website: 'https://golem.network/',
  },
  gold: {
    icon: require('cryptocurrency-icons/128/color/gold.png'),
    color: '#F1B32B',
    description: '',
    website: '',
  },
  grc: {
    icon: require('cryptocurrency-icons/128/color/grc.png'),
    color: '#5412B4',
    description: '',
    website: '',
  },
  grin: {
    icon: require('cryptocurrency-icons/128/color/grin.png'),
    color: '#FFF300',
    description: '',
    website: '',
  },
  grs: {
    icon: require('cryptocurrency-icons/128/color/grs.png'),
    color: '#377E96',
    description: '',
    website: '',
  },
  grt: {
    icon: require('../../assets/cryptos/grt.png'),
    color: '#6747ED',
    description: 'The Graph (GRT) is an Ethereum token that powers The Graph, a decentralized protocol for indexing and querying data from blockchains. Just as Google indexes the web, The Graph indexes blockchain data from networks like Ethereum and Filecoin. This data is grouped into open APIs called subgraphs that anyone can query.',
    website: 'https://thegraph.com/',
  },
  gsc: {
    icon: require('cryptocurrency-icons/128/color/gsc.png'),
    color: '#FF0060',
    description: '',
    website: '',
  },
  gtc: {
    icon: require('../../assets/cryptos/gtc.png'),
    color: '#02E2AC',
    description: 'Gitcoin (GTC) is an Ethereum token that enables community governance of the Gitcoin platform. The platform is designed to fund and coordinate open source development by novel means such as quadratic funding. As of June 2021, Gitcoin has facilitated over $21 million in grants and bounties for open source developers.',
    website: 'https://gitcoin.co/',
  },
  gto: {
    icon: require('cryptocurrency-icons/128/color/gto.png'),
    color: '#7F27FF',
    description: '',
    website: '',
  },
  gup: {
    icon: require('cryptocurrency-icons/128/color/gup.png'),
    color: '#37DCD8',
    description: '',
    website: '',
  },
  gusd: {
    icon: require('cryptocurrency-icons/128/color/gusd.png'),
    color: '#00DCFA',
    description: '',
    website: '',
  },
  gvt: {
    icon: require('cryptocurrency-icons/128/color/gvt.png'),
    color: '#16B9AD',
    description: '',
    website: '',
  },
  gxs: {
    icon: require('cryptocurrency-icons/128/color/gxs.png'),
    color: '#35A5F3',
    description: '',
    website: '',
  },
  gzr: {
    icon: require('cryptocurrency-icons/128/color/gzr.png'),
    color: '#56C9E9',
    description: '',
    website: '',
  },
  hight: {
    icon: require('cryptocurrency-icons/128/color/hight.png'),
    color: '#117FC0',
    description: '',
    website: '',
  },
  hodl: {
    icon: require('cryptocurrency-icons/128/color/hodl.png'),
    color: '#D59143',
    description: '',
    website: '',
  },
  hot: {
    icon: require('cryptocurrency-icons/128/color/hot.png'),
    color: '#8734FE',
    description: '',
    website: '',
  },
  hpb: {
    icon: require('cryptocurrency-icons/128/color/hpb.png'),
    color: '#1591CA',
    description: '',
    website: '',
  },
  hsr: {
    icon: require('cryptocurrency-icons/128/color/hsr.png'),
    color: '#56428E',
    description: '',
    website: '',
  },
  ht: {
    icon: require('cryptocurrency-icons/128/color/ht.png'),
    color: '#2A3069',
    description: '',
    website: '',
  },
  html: {
    icon: require('cryptocurrency-icons/128/color/html.png'),
    color: '#CFA967',
    description: '',
    website: '',
  },
  huc: {
    icon: require('cryptocurrency-icons/128/color/huc.png'),
    color: '#FFC018',
    description: '',
    website: '',
  },
  hush: {
    icon: require('cryptocurrency-icons/128/color/hush.png'),
    color: '#292929',
    description: '',
    website: '',
  },
  icn: {
    icon: require('cryptocurrency-icons/128/color/icn.png'),
    color: '#4C6F8C',
    description: '',
    website: '',
  },
  icp: {
    icon: require('../../assets/cryptos/icp.png'),
    color: '#29ABE2',
    description: 'Internet Computer (ICP) is a utility token that allows users to participate in and govern the Internet Computer blockchain network. The network aims to help developers create websites, enterprise IT systems, internet services, and DeFi applications by "installing their code directly on the public Internet." ICP can also be staked or "converted into cycles" that can be used to power computation for dApps and traditional applications.',
    website: 'https://dfinity.org/',
  },
  icx: {
    icon: require('cryptocurrency-icons/128/color/icx.png'),
    color: '#1FC5C9',
    description: '',
    website: '',
  },
  ignis: {
    icon: require('cryptocurrency-icons/128/color/ignis.png'),
    color: '#F9C011',
    description: '',
    website: '',
  },
  ilk: {
    icon: require('cryptocurrency-icons/128/color/ilk.png'),
    color: '#98C23A',
    description: '',
    website: '',
  },
  ink: {
    icon: require('cryptocurrency-icons/128/color/ink.png'),
    color: '#DF1A14',
    description: '',
    website: '',
  },
  ins: {
    icon: require('cryptocurrency-icons/128/color/ins.png'),
    color: '#B2A3F6',
    description: '',
    website: '',
  },
  ion: {
    icon: require('cryptocurrency-icons/128/color/ion.png'),
    color: '#57BEEA',
    description: '',
    website: '',
  },
  iop: {
    icon: require('cryptocurrency-icons/128/color/iop.png'),
    color: '#0CAFA5',
    description: '',
    website: '',
  },
  iost: {
    icon: require('cryptocurrency-icons/128/color/iost.png'),
    color: '#1C1C1C',
    description: '',
    website: '',
  },
  iotx: {
    icon: require('cryptocurrency-icons/128/color/iotx.png'),
    color: '#00D4D5',
    description: '',
    website: '',
  },
  iq: {
    icon: require('cryptocurrency-icons/128/color/iq.png'),
    color: '#55DDFF',
    description: '',
    website: '',
  },
  itc: {
    icon: require('cryptocurrency-icons/128/color/itc.png'),
    color: '#102044',
    description: '',
    website: '',
  },
  jnt: {
    icon: require('cryptocurrency-icons/128/color/jnt.png'),
    color: '#0050DB',
    description: '',
    website: '',
  },
  jpy: {
    icon: require('cryptocurrency-icons/128/color/jpy.png'),
    color: '#EAC749',
    description: '',
    website: '',
  },
  kcs: {
    icon: require('cryptocurrency-icons/128/color/kcs.png'),
    color: '#0093DD',
    description: '',
    website: '',
  },
  keep: {
    icon: require('../../assets/cryptos/keep.png'),
    color: '#000000',
    description: 'KEEP is an Ethereum token that powers the Keep Network, a platform that aims to bridge public blockchains and private data. One of Keep Network’s first products is an Ethereum token that represents 1 Bitcoin, called tBTC. Keep Network enables users to deposit Bitcoin and redeem tokenized tBTC, which can then be used in the Ethereum ecosystem without centralized intermediaries.',
    website: 'https://keep.network/',
  },
  kin: {
    icon: require('cryptocurrency-icons/128/color/kin.png'),
    color: '#005FFF',
    description: '',
    website: '',
  },
  klown: {
    icon: require('cryptocurrency-icons/128/color/klown.png'),
    color: '#EA0017',
    description: '',
    website: '',
  },
  kmd: {
    icon: require('cryptocurrency-icons/128/color/kmd.png'),
    color: '#2B6680',
    description: '',
    website: '',
  },
  knc: {
    icon: require('cryptocurrency-icons/128/color/knc.png'),
    color: '#31CB9E',
    description: 'KNC is an Ethereum token used for paying fees on the Kyber Network, a protocol that aims to make swapping digital assets and cryptocurrencies simple and efficient.',
    website: 'https://kyber.network/',
  },
  krb: {
    icon: require('cryptocurrency-icons/128/color/krb.png'),
    color: '#00AEEF',
    description: '',
    website: '',
  },
  lbc: {
    icon: require('cryptocurrency-icons/128/color/lbc.png'),
    color: '#006148',
    description: '',
    website: '',
  },
  lend: {
    icon: require('cryptocurrency-icons/128/color/lend.png'),
    color: '#0FA9C9',
    description: '',
    website: '',
  },
  leo: {
    icon: require('cryptocurrency-icons/128/color/leo.png'),
    color: '#11021E',
    description: '',
    website: '',
  },
  link: {
    icon: require('cryptocurrency-icons/128/color/link.png'),
    color: '#2A5ADA',
    description: 'Chainlink (LINK) is an Ethereum token that powers the Chainlink decentralized oracle network. This network allows smart contracts on Ethereum to securely connect to external data sources, APIs, and payment systems.',
    website: 'https://chain.link/',
  },
  lkk: {
    icon: require('cryptocurrency-icons/128/color/lkk.png'),
    color: '#9D01EB',
    description: '',
    website: '',
  },
  loom: {
    icon: require('cryptocurrency-icons/128/color/loom.png'),
    color: '#48BEFE',
    description: 'Loom Network (LOOM) is an Ethereum token that powers a network of delegated proof of stake sidechains (a system that Loom dubs “EOS on Ethereum”). This allows for highly-scalable games and user-facing dApps backed by the security of Ethereum.',
    website: 'https://loomx.io/',
  },
  lpt: {
    icon: require('../../assets/cryptos/lpt.png'),
    color: '#40D094',
    description: 'LPT is an Ethereum token that powers the Livepeer network, a platform for decentralized video streaming. LPT is required to perform the work of transcoding and distributing video on the network while also incentivizing peers to ensure that the network is cost-effective and secure.',
    website: 'https://livepeer.org/primer',
  },
  lrc: {
    icon: require('cryptocurrency-icons/128/color/lrc.png'),
    color: '#2AB5F6',
    description: 'Loopring is an Ethereum token that describes itself as “an open-sourced, audited, and non-custodial exchange protocol.” It aims to allow anyone to build non-custodial, order book-based exchanges on Ethereum by leveraging zero-knowledge proofs.',
    website: 'https://loopring.org/',
  },
  lsk: {
    icon: require('cryptocurrency-icons/128/color/lsk.png'),
    color: '#0D4EA0',
    description: '',
    website: '',
  },
  ltc: {
    icon: require('cryptocurrency-icons/128/color/ltc.png'),
    color: '#BFBBBB',
    description: 'Litecoin is a cryptocurrency that uses a faster payment confirmation schedule and a different cryptographic algorithm than Bitcoin.',
    website: 'https://litecoin.org/',
  },
  lun: {
    icon: require('cryptocurrency-icons/128/color/lun.png'),
    color: '#F55749',
    description: '',
    website: '',
  },
  maid: {
    icon: require('cryptocurrency-icons/128/color/maid.png'),
    color: '#5692D8',
    description: '',
    website: '',
  },
  mana: {
    icon: require('cryptocurrency-icons/128/color/mana.png'),
    color: '#FF2C55',
    description: 'Decentraland (MANA) is an Ethereum token that powers the Decentraland virtual reality platform. MANA can be used to pay for virtual plots of land in Decentraland as well as in-world goods and services.',
    website: 'https://decentraland.org/',
  },
  mask: {
    icon: require('../../assets/cryptos/mask.png'),
    color: '#1C68F3',
    description: 'Mask Network enables users of popular social media platforms to send cryptocurrency, interact with decentralized applications, and share encrypted content. MASK token holders can vote on ecosystem initiatives via a decentralized autonomous organization called MaskDAO.',
    website: 'https://mask.io/',
  },
  matic: {
    icon: require('../../assets/cryptos/matic.png'),
    color: '#8247E5',
    description: 'Polygon was formerly called Matic Network. Polygon (MATIC) is an Ethereum token that powers the Polygon Network, a scaling solution for Ethereum. Polygon aims to provide faster and cheaper transactions on Ethereum using Layer 2 sidechains, which are blockchains that run alongside the Ethereum main chain. Users can deposit Ethereum tokens to a Polygon smart contract, interact with them within Polygon, and then later withdraw them back to the Ethereum main chain. The MATIC token is used to pay transaction fees and participate in proof-of-stake consensus.',
    website: 'https://polygon.technology/',
  },
  mcap: {
    icon: require('cryptocurrency-icons/128/color/mcap.png'),
    color: '#033B4A',
    description: '',
    website: '',
  },
  mco: {
    icon: require('cryptocurrency-icons/128/color/mco.png'),
    color: '#103F68',
    description: '',
    website: '',
  },
  mda: {
    icon: require('cryptocurrency-icons/128/color/mda.png'),
    color: '#01A64F',
    description: '',
    website: '',
  },
  mds: {
    icon: require('cryptocurrency-icons/128/color/mds.png'),
    color: '#1E252C',
    description: '',
    website: '',
  },
  med: {
    icon: require('cryptocurrency-icons/128/color/med.png'),
    color: '#00B0FF',
    description: '',
    website: '',
  },
  meetone: {
    icon: require('cryptocurrency-icons/128/color/meetone.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  mft: {
    icon: require('cryptocurrency-icons/128/color/mft.png'),
    color: '#DA1157',
    description: '',
    website: '',
  },
  miota: {
    icon: require('cryptocurrency-icons/128/color/miota.png'),
    color: '#242424',
    description: '',
    website: '',
  },
  mir: {
    icon: require('../../assets/cryptos/mir.png'),
    color: '#232C45',
    description: 'MIR is an Ethereum token that governs the Mirror Protocol which “allows the creation of fungible assets, that track the price of real world assets.” The project aims to enable 24/7 equities trading by minting “synthetic” versions of the real thing. MIR tokens can be used to propose and vote on important changes to the protocol.',
    website: 'https://mirror.finance/',
  },
  mith: {
    icon: require('cryptocurrency-icons/128/color/mith.png'),
    color: '#00316D',
    description: '',
    website: '',
  },
  mkr: {
    icon: require('cryptocurrency-icons/128/color/mkr.png'),
    color: '#1AAB9B',
    description: 'Maker is an Ethereum token that describes itself as “a utility token, governance token, and recapitalization resource of the Maker system.” The purpose of the Maker system is to generate another Ethereum token, called Dai, that seeks to trade on exchanges at a value of exactly US$1.00.',
    website: 'https://makerdao.com/',
  },
  mln: {
    icon: require('../../assets/cryptos/mln.png'),
    color: '#3B82F6',
    description: 'MLN is an Ethereum token that powers Enzyme (formerly known as Melon Protocol), a protocol that aims to facilitate on-chain asset management for the DeFi ecosystem. MLN allows users to build, share, and explore DeFi investment strategies (called “vaults”) while filtering by historical performance and risk profiles. MLN is used to pay for various functions throughout the vault creation process and investment lifecycle.',
    website: 'https://enzyme.finance/',
  },
  mnx: {
    icon: require('cryptocurrency-icons/128/color/mnx.png'),
    color: '#00ADEF',
    description: '',
    website: '',
  },
  mnz: {
    icon: require('cryptocurrency-icons/128/color/mnz.png'),
    color: '#7F368A',
    description: '',
    website: '',
  },
  moac: {
    icon: require('cryptocurrency-icons/128/color/moac.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  mod: {
    icon: require('cryptocurrency-icons/128/color/mod.png'),
    color: '#09547D',
    description: '',
    website: '',
  },
  mona: {
    icon: require('cryptocurrency-icons/128/color/mona.png'),
    color: '#DEC799',
    description: '',
    website: '',
  },
  msr: {
    icon: require('cryptocurrency-icons/128/color/msr.png'),
    color: '#47B85C',
    description: '',
    website: '',
  },
  mth: {
    icon: require('cryptocurrency-icons/128/color/mth.png'),
    color: '#104FCA',
    description: '',
    website: '',
  },
  mtl: {
    icon: require('cryptocurrency-icons/128/color/mtl.png'),
    color: '#1E1F25',
    description: '',
    website: '',
  },
  music: {
    icon: require('cryptocurrency-icons/128/color/music.png'),
    color: '#FBBF02',
    description: '',
    website: '',
  },
  mzc: {
    icon: require('cryptocurrency-icons/128/color/mzc.png'),
    color: '#FFAA05',
    description: '',
    website: '',
  },
  nano: {
    icon: require('cryptocurrency-icons/128/color/nano.png'),
    color: '#4A90E2',
    description: '',
    website: '',
  },
  nas: {
    icon: require('cryptocurrency-icons/128/color/nas.png'),
    color: '#222222',
    description: '',
    website: '',
  },
  nav: {
    icon: require('cryptocurrency-icons/128/color/nav.png'),
    color: '#7D59B5',
    description: '',
    website: '',
  },
  ncash: {
    icon: require('cryptocurrency-icons/128/color/ncash.png'),
    color: '#36A9CF',
    description: '',
    website: '',
  },
  ndz: {
    icon: require('cryptocurrency-icons/128/color/ndz.png'),
    color: '#622FBA',
    description: '',
    website: '',
  },
  nebl: {
    icon: require('cryptocurrency-icons/128/color/nebl.png'),
    color: '#50479E',
    description: '',
    website: '',
  },
  neo: {
    icon: require('cryptocurrency-icons/128/color/neo.png'),
    color: '#58BF00',
    description: '',
    website: '',
  },
  neos: {
    icon: require('cryptocurrency-icons/128/color/neos.png'),
    color: '#E5F300',
    description: '',
    website: '',
  },
  neu: {
    icon: require('cryptocurrency-icons/128/color/neu.png'),
    color: '#B3BA00',
    description: '',
    website: '',
  },
  nexo: {
    icon: require('cryptocurrency-icons/128/color/nexo.png'),
    color: '#1A4199',
    description: '',
    website: '',
  },
  ngc: {
    icon: require('cryptocurrency-icons/128/color/ngc.png'),
    color: '#F80000',
    description: '',
    website: '',
  },
  nio: {
    icon: require('cryptocurrency-icons/128/color/nio.png'),
    color: '#70C9C9',
    description: '',
    website: '',
  },
  nkn: {
    icon: require('../../assets/cryptos/nkn.png'),
    color: '#253A7E',
    description: 'New Kind of Network (NKN) is a public blockchain that aims to use economic incentives to motivate Internet users to share network connections and utilize unused bandwidth. NKN aims to be a network for building decentralized applications in a way that enhances peer-to-peer data transmission and connectivity.',
    website: 'https://nkn.org/',
  },
  nlc2: {
    icon: require('cryptocurrency-icons/128/color/nlc2.png'),
    color: '#F28F01',
    description: '',
    website: '',
  },
  nlg: {
    icon: require('cryptocurrency-icons/128/color/nlg.png'),
    color: '#2AB0FD',
    description: '',
    website: '',
  },
  nmc: {
    icon: require('cryptocurrency-icons/128/color/nmc.png'),
    color: '#186C9D',
    description: '',
    website: '',
  },
  nmr: {
    icon: require('cryptocurrency-icons/128/color/nmr.png'),
    color: '#000000',
    description: 'Numeraire is an Ethereum token that powers Numerai, a San Francisco-based hedge fund that crowdsources artificial intelligence to make investments in major stock markets around the world. Numeraire (NMR) holders can stake their NMR tokens every week on specific predictions. Successful predictions are rewarded with more NMR.',
    website: 'https://numer.ai/',
  },
  npxs: {
    icon: require('cryptocurrency-icons/128/color/npxs.png'),
    color: '#F5D100',
    description: '',
    website: '',
  },
  nu: {
    icon: require('../../assets/cryptos/nu.png'),
    color: '#1D64FA',
    description: 'NuCypher (NU) is an Ethereum token that can be staked to run a node on the NuCypher network. NuCypher describes itself as a threshold cryptography network that provides data privacy and key management for decentralized applications and protocols.',
    website: 'https://www.nucypher.com/',
  },
  nuls: {
    icon: require('cryptocurrency-icons/128/color/nuls.png'),
    color: '#81BD39',
    description: '',
    website: '',
  },
  nxs: {
    icon: require('cryptocurrency-icons/128/color/nxs.png'),
    color: '#4099CD',
    description: '',
    website: '',
  },
  nxt: {
    icon: require('cryptocurrency-icons/128/color/nxt.png'),
    color: '#008FBB',
    description: '',
    website: '',
  },
  oax: {
    icon: require('cryptocurrency-icons/128/color/oax.png'),
    color: '#164B79',
    description: '',
    website: '',
  },
  ogn: {
    icon: require('../../assets/cryptos/ogn.png'),
    color: '#2087FB',
    description: 'Origin Token (OGN) is an Ethereum token that powers the Origin platform, which aims to power decentralized and peer-to-peer marketplaces. OGN can be used for staking, governance, and advertising on the Origin platform.',
    website: 'https://www.originprotocol.com/',
  },
  ok: {
    icon: require('cryptocurrency-icons/128/color/ok.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  omg: {
    icon: require('cryptocurrency-icons/128/color/omg.png'),
    color: '#101010',
    description: 'The OMG Network (formerly OmiseGO) is a value transfer network for Ethereum and any ERC-20 token. It describes itself as the first production-grade layer-2 Ethereum scaling solution and aims to let people move money and a variety of digital values on the blockchain faster, cheaper, and without compromising on security.',
    website: 'https://omg.network/',
  },
  omni: {
    icon: require('cryptocurrency-icons/128/color/omni.png'),
    color: '#1C347A',
    description: '',
    website: '',
  },
  ong: {
    icon: require('cryptocurrency-icons/128/color/ong.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  ont: {
    icon: require('cryptocurrency-icons/128/color/ont.png'),
    color: '#32A4BE',
    description: '',
    website: '',
  },
  oot: {
    icon: require('cryptocurrency-icons/128/color/oot.png'),
    color: '#25AAE1',
    description: '',
    website: '',
  },
  orn: {
    icon: require('../../assets/cryptos/orn.png'),
    color: '#313151',
    description: 'ORN is an Ethereum token that powers Orion Protocol, which aims to aggregate liquidity from centralized and decentralized exchanges into one platform. ORN can be used to receive discounted trading fees, for staking, and to access advanced features within the Orion Protocol.',
    website: 'https://www.orionprotocol.io/orn',
  },
  ost: {
    icon: require('cryptocurrency-icons/128/color/ost.png'),
    color: '#34445B',
    description: '',
    website: '',
  },
  ox: {
    icon: require('cryptocurrency-icons/128/color/ox.png'),
    color: '#4392CD',
    description: '',
    website: '',
  },
  oxt: {
    icon: require('cryptocurrency-icons/128/color/oxt.png'),
    color: '#5E45BA',
    description: 'Orchid (OXT) is an Ethereum token that powers the Orchid network, a peer-to-peer privacy tool that includes a decentralized VPN and other features designed to give users more control over their Internet connection. OXT can be used to pay for bandwidth or staked by bandwidth providers in order to operate a node.',
    website: 'https://www.orchid.com/',
  },
  part: {
    icon: require('cryptocurrency-icons/128/color/part.png'),
    color: '#03E8B0',
    description: '',
    website: '',
  },
  pasc: {
    icon: require('cryptocurrency-icons/128/color/pasc.png'),
    color: '#F7931E',
    description: '',
    website: '',
  },
  pasl: {
    icon: require('cryptocurrency-icons/128/color/pasl.png'),
    color: '#00ACFF',
    description: '',
    website: '',
  },
  pax: {
    icon: require('cryptocurrency-icons/128/color/pax.png'),
    color: '#EDE708',
    description: '',
    website: '',
  },
  pay: {
    icon: require('cryptocurrency-icons/128/color/pay.png'),
    color: '#302C2C',
    description: '',
    website: '',
  },
  payx: {
    icon: require('cryptocurrency-icons/128/color/payx.png'),
    color: '#663300',
    description: '',
    website: '',
  },
  pink: {
    icon: require('cryptocurrency-icons/128/color/pink.png'),
    color: '#ED79AA',
    description: '',
    website: '',
  },
  pirl: {
    icon: require('cryptocurrency-icons/128/color/pirl.png'),
    color: '#96B73D',
    description: '',
    website: '',
  },
  pivx: {
    icon: require('cryptocurrency-icons/128/color/pivx.png'),
    color: '#5E4778',
    description: '',
    website: '',
  },
  pla: {
    icon: require('../../assets/cryptos/pla.png'),
    color: '#02D6B4',
    description: 'PLA is an Ethereum token that powers PlayDapp, a blockchain gaming platform and non-fungible token (NFT) marketplace. PLA acts as the primary token for processing transactions on PlayDapp. Game developers can also receive PLA when users make in-game purchases.',
    website: 'https://playdapp.io/',
  },
  plr: {
    icon: require('cryptocurrency-icons/128/color/plr.png'),
    color: '#00BFFF',
    description: '',
    website: '',
  },
  poa: {
    icon: require('cryptocurrency-icons/128/color/poa.png'),
    color: '#444FA1',
    description: '',
    website: '',
  },
  poe: {
    icon: require('cryptocurrency-icons/128/color/poe.png'),
    color: '#DCD6CC',
    description: '',
    website: '',
  },
  polis: {
    icon: require('cryptocurrency-icons/128/color/polis.png'),
    color: '#2C3E50',
    description: '',
    website: '',
  },
  poly: {
    icon: require('cryptocurrency-icons/128/color/poly.png'),
    color: '#4C5A95',
    description: '',
    website: '',
  },
  pot: {
    icon: require('cryptocurrency-icons/128/color/pot.png'),
    color: '#105B2F',
    description: '',
    website: '',
  },
  powr: {
    icon: require('cryptocurrency-icons/128/color/powr.png'),
    color: '#05BCA9',
    description: '',
    website: '',
  },
  ppc: {
    icon: require('cryptocurrency-icons/128/color/ppc.png'),
    color: '#3CB054',
    description: '',
    website: '',
  },
  ppp: {
    icon: require('cryptocurrency-icons/128/color/ppp.png'),
    color: '#348F8D',
    description: '',
    website: '',
  },
  ppt: {
    icon: require('cryptocurrency-icons/128/color/ppt.png'),
    color: '#152743',
    description: '',
    website: '',
  },
  pre: {
    icon: require('cryptocurrency-icons/128/color/pre.png'),
    color: '#3A8CBD',
    description: '',
    website: '',
  },
  prl: {
    icon: require('cryptocurrency-icons/128/color/prl.png'),
    color: '#1061E3',
    description: '',
    website: '',
  },
  pungo: {
    icon: require('cryptocurrency-icons/128/color/pungo.png'),
    color: '#22B573',
    description: '',
    website: '',
  },
  pura: {
    icon: require('cryptocurrency-icons/128/color/pura.png'),
    color: '#333333',
    description: '',
    website: '',
  },
  qash: {
    icon: require('cryptocurrency-icons/128/color/qash.png'),
    color: '#1347E8',
    description: '',
    website: '',
  },
  qiwi: {
    icon: require('cryptocurrency-icons/128/color/qiwi.png'),
    color: '#FF8C00',
    description: '',
    website: '',
  },
  qlc: {
    icon: require('cryptocurrency-icons/128/color/qlc.png'),
    color: '#610089',
    description: '',
    website: '',
  },
  qnt: {
    icon: require('../../assets/cryptos/qnt.png'),
    color: '#EF4F1F',
    description: 'QNT is an Ethereum token that is used to power Quant Network’s Overledger brand of enterprise software solutions, which aim to connect public blockchains and private networks. Quant Network allows the creation of so-called mDapps that enable decentralized applications to operate on multiple blockchains at once.',
    website: 'https://www.quant.network/',
  },
  qrl: {
    icon: require('cryptocurrency-icons/128/color/qrl.png'),
    color: '#252525',
    description: '',
    website: '',
  },
  qsp: {
    icon: require('cryptocurrency-icons/128/color/qsp.png'),
    color: '#454545',
    description: '',
    website: '',
  },
  qtum: {
    icon: require('cryptocurrency-icons/128/color/qtum.png'),
    color: '#2E9AD0',
    description: '',
    website: '',
  },
  quick: {
    icon: require('../../assets/cryptos/quick.png'),
    color: '#418AC9',
    description: 'QUICK is an Ethereum token that powers QuickSwap, a decentralized exchange that runs on the Polygon Network in order to provide faster and cheaper transactions on Ethereum. QUICK can be used to create and vote on proposals governing QuickSwap and can be staked to earn a portion of trading fees.',
    website: 'https://quickswap.exchange/',
  },
  r: {
    icon: require('cryptocurrency-icons/128/color/r.png'),
    color: '#771A4E',
    description: '',
    website: '',
  },
  rads: {
    icon: require('cryptocurrency-icons/128/color/rads.png'),
    color: '#9D4BEF',
    description: '',
    website: '',
  },
  rai: {
    icon: require('../../assets/cryptos/rai.png'),
    color: '#243134',
    description: 'RAI is an Ethereum token that aims to maintain a stable value. The RAI-USD exchange rate is determined by supply and demand while the protocol that issues RAI tries to stabilize its price by constantly de- or re-valuing it. The supply and demand mechanic plays out between two parties: SAFE users (those who generate RAI with their ETH) and RAI holders (those who hold, speculate on or use RAI in other protocols and apps).',
    website: 'https://reflexer.finance/',
  },
  rap: {
    icon: require('cryptocurrency-icons/128/color/rap.png'),
    color: '#000000',
    description: '',
    website: '',
  },
  rcn: {
    icon: require('cryptocurrency-icons/128/color/rcn.png'),
    color: '#3555F9',
    description: '',
    website: '',
  },
  rdd: {
    icon: require('cryptocurrency-icons/128/color/rdd.png'),
    color: '#E30613',
    description: '',
    website: '',
  },
  rdn: {
    icon: require('cryptocurrency-icons/128/color/rdn.png'),
    color: '#2A2A2A',
    description: '',
    website: '',
  },
  ren: {
    icon: require('cryptocurrency-icons/128/color/ren.png'),
    color: '#001E3D',
    description: 'Ren (REN) is an Ethereum token that powers Ren’s open protocol for transferring cryptocurrencies between blockchains. Ren aims to bring popular assets like Bitcoin and Zcash to blockchains including Ethereum, making it possible for these assets to participate in a multi-chain decentralized finance ecosystem.',
    website: 'https://renproject.io/',
  },
  rep: {
    icon: require('cryptocurrency-icons/128/color/rep.png'),
    color: '#612A52',
    description: 'Augur’s Reputation token (REP) is an Ethereum token designed for reporting and disputing the outcome of events on online prediction markets. Reporters are rewarded for reporting the outcome of events correctly.',
    website: 'https://www.augur.net/',
  },
  repv2: {
    icon: require('cryptocurrency-icons/128/color/repv2.png'),
    color: '#0E0E21',
    description: '',
    website: '',
  },
  req: {
    icon: require('cryptocurrency-icons/128/color/req.png'),
    color: '#00E6A0',
    description: '',
    website: '',
  },
  rhoc: {
    icon: require('cryptocurrency-icons/128/color/rhoc.png'),
    color: '#CC1E46',
    description: '',
    website: '',
  },
  ric: {
    icon: require('cryptocurrency-icons/128/color/ric.png'),
    color: '#61E4DE',
    description: '',
    website: '',
  },
  rise: {
    icon: require('cryptocurrency-icons/128/color/rise.png'),
    color: '#F49352',
    description: '',
    website: '',
  },
  rlc: {
    icon: require('cryptocurrency-icons/128/color/rlc.png'),
    color: '#FFD800',
    description: 'RLC is an Ethereum token for the iExec cloud platform in which users can monetize and rent computing power and data. iExec enables developers to power applications on what is described as “a decentralized marketplace for cloud resources."',
    website: 'https://iex.ec/',
  },
  rly: {
    icon: require('../../assets/cryptos/rly.png'),
    color: '#FF8A03',
    description: 'RLY is an Ethereum token that powers the Rally network. Rally enables creators and online communities to launch their own cryptocurrencies. By creating these so-called “social tokens,” fans can gain access to benefits like unreleased content or merch, while creators can unlock new forms of revenue.',
    website: 'https://rally.io/',
  },
  rpx: {
    icon: require('cryptocurrency-icons/128/color/rpx.png'),
    color: '#8D181B',
    description: '',
    website: '',
  },
  rub: {
    icon: require('cryptocurrency-icons/128/color/rub.png'),
    color: '#65D1FF',
    description: '',
    website: '',
  },
  rvn: {
    icon: require('cryptocurrency-icons/128/color/rvn.png'),
    color: '#384182',
    description: '',
    website: '',
  },
  ryo: {
    icon: require('cryptocurrency-icons/128/color/ryo.png'),
    color: '#3D58B0',
    description: '',
    website: '',
  },
  safe: {
    icon: require('cryptocurrency-icons/128/color/safe.png'),
    color: '#00688D',
    description: '',
    website: '',
  },
  sai: {
    icon: require('cryptocurrency-icons/128/color/sai.png'),
    color: '#B68900',
    description: '',
    website: '',
  },
  salt: {
    icon: require('cryptocurrency-icons/128/color/salt.png'),
    color: '#1BEEF4',
    description: '',
    website: '',
  },
  san: {
    icon: require('cryptocurrency-icons/128/color/san.png'),
    color: '#2B77B3',
    description: '',
    website: '',
  },
  sbd: {
    icon: require('cryptocurrency-icons/128/color/sbd.png'),
    color: '#56A8F3',
    description: '',
    website: '',
  },
  sberbank: {
    icon: require('cryptocurrency-icons/128/color/sberbank.png'),
    color: '#48B254',
    description: '',
    website: '',
  },
  sc: {
    icon: require('cryptocurrency-icons/128/color/sc.png'),
    color: '#20EE82',
    description: '',
    website: '',
  },
  shib: {
    icon: require('../../assets/cryptos/shib.png'),
    color: '#1C2951',
    description: 'Shiba Inu (SHIB) is a token that aspires to be an Ethereum-based alternative to Dogecoin (DOGE), the popular memecoin. Unlike Bitcoin, which is designed to be scarce, SHIB is intentionally abundant — with a circulating supply of one quadrillion. The Shiba Inu Token ecosystem supports projects such as an NFT art incubator and the development of a decentralized exchange called Shibaswap.',
    website: 'https://shibatoken.com/',
  },
  shift: {
    icon: require('cryptocurrency-icons/128/color/shift.png'),
    color: '#964B9C',
    description: '',
    website: '',
  },
  sib: {
    icon: require('cryptocurrency-icons/128/color/sib.png'),
    color: '#057BC1',
    description: '',
    website: '',
  },
  sin: {
    icon: require('cryptocurrency-icons/128/color/sin.png'),
    color: '#F5342E',
    description: '',
    website: '',
  },
  skl: {
    icon: require('../../assets/cryptos/skl.png'),
    color: '#000000',
    description: 'SKALE (SKL) is an Ethereum token that powers the Skale Network, which describes itself as “an Ethereum-compatible network with a leaderless consensus designed to run on an uncapped number of independent nodes.” Nodes on the Skale Network provide resources to multiple decentralized elastic blockchains. The SKL token grants a right to participate as a network validator, stake as a delegator, or access a share of the network’s resources as a developer.',
    website: 'https://skale.network/',
  },
  sky: {
    icon: require('cryptocurrency-icons/128/color/sky.png'),
    color: '#0072FF',
    description: '',
    website: '',
  },
  slr: {
    icon: require('cryptocurrency-icons/128/color/slr.png'),
    color: '#FDA616',
    description: '',
    website: '',
  },
  sls: {
    icon: require('cryptocurrency-icons/128/color/sls.png'),
    color: '#8E9495',
    description: '',
    website: '',
  },
  smart: {
    icon: require('cryptocurrency-icons/128/color/smart.png'),
    color: '#FEC60D',
    description: '',
    website: '',
  },
  sngls: {
    icon: require('cryptocurrency-icons/128/color/sngls.png'),
    color: '#B30D23',
    description: '',
    website: '',
  },
  snm: {
    icon: require('cryptocurrency-icons/128/color/snm.png'),
    color: '#0B1C26',
    description: '',
    website: '',
  },
  snt: {
    icon: require('cryptocurrency-icons/128/color/snt.png'),
    color: '#5B6DEE',
    description: '',
    website: '',
  },
  snx: {
    icon: require('../../assets/cryptos/snx.png'),
    color: '#090220',
    description: 'Synthetix Network Token(SNX) is an Ethereum token that powers Synthetix, a decentralised synthetic asset issuance protocol. Synthetic assets are minted when token holders stake their SNX as collateral using Mintr, a decentralised application for interacting with the Synthetix contracts. The protocol currently supports synthetic fiat currencies, cryptocurrencies, and commodities.',
    website: 'https://www.synthetix.io/',
  },
  soc: {
    icon: require('cryptocurrency-icons/128/color/soc.png'),
    color: '#199248',
    description: '',
    website: '',
  },
  sol: {
    icon: require('../../assets/cryptos/sol.png'),
    color: '#00FFBD',
    description: 'Solana is a decentralized computing platform that uses SOL to pay for transactions. Solana aims to improve blockchain scalability by using a combination of proof of stake consensus and so-called proof of history. As a result, Solana claims to be able to support 50,000 transactions per second without sacrificing decentralization.',
    website: 'https://solana.com/',
  },
  spank: {
    icon: require('cryptocurrency-icons/128/color/spank.png'),
    color: '#FF3B81',
    description: '',
    website: '',
  },
  sphtx: {
    icon: require('cryptocurrency-icons/128/color/sphtx.png'),
    color: '#2CBEAA',
    description: '',
    website: '',
  },
  srn: {
    icon: require('cryptocurrency-icons/128/color/srn.png'),
    color: '#1C1C1C',
    description: '',
    website: '',
  },
  stak: {
    icon: require('cryptocurrency-icons/128/color/stak.png'),
    color: '#F2941B',
    description: '',
    website: '',
  },
  start: {
    icon: require('cryptocurrency-icons/128/color/start.png'),
    color: '#01AEF0',
    description: '',
    website: '',
  },
  steem: {
    icon: require('cryptocurrency-icons/128/color/steem.png'),
    color: '#4BA2F2',
    description: '',
    website: '',
  },
  storj: {
    icon: require('cryptocurrency-icons/128/color/storj.png'),
    color: '#2683FF',
    description: 'Storj (STORJ) is an Ethereum token that powers a decentralized cloud storage network for developers called Storj DCS (Decentralized Cloud Storage). After a customer uploads a file to Storj DCS, pieces of each file are distributed to a global network of independent nodes. When someone requests the file, it is then recompiled securely and made available for download. This means that anyone can store files on Storj DCS without having to trust a centralized data center. Developers can purchase cloud storage services with STORJ. Network participants earn STORJ in return for providing unused hard drive space and bandwidth to the network.',
    website: 'https://storj.io/',
  },
  storm: {
    icon: require('cryptocurrency-icons/128/color/storm.png'),
    color: '#080D98',
    description: '',
    website: '',
  },
  stq: {
    icon: require('cryptocurrency-icons/128/color/stq.png'),
    color: '#2EC4E7',
    description: '',
    website: '',
  },
  strat: {
    icon: require('cryptocurrency-icons/128/color/strat.png'),
    color: '#1387C9',
    description: '',
    website: '',
  },
  stx: {
    icon: require('cryptocurrency-icons/128/color/stx.png'),
    color: '#7324F0',
    description: '',
    website: '',
  },
  sub: {
    icon: require('cryptocurrency-icons/128/color/sub.png'),
    color: '#E53431',
    description: '',
    website: '',
  },
  sumo: {
    icon: require('cryptocurrency-icons/128/color/sumo.png'),
    color: '#2D9CDB',
    description: '',
    website: '',
  },
  sushi: {
    icon: require('../../assets/cryptos/sushi.png'),
    color: '#F056A3',
    description: 'SushiSwap (SUSHI) is an Ethereum token that powers SushiSwap, a decentralized cryptocurrency exchange and automated market maker built on Ethereum. Holders of SUSHI can participate in community governance and stake their tokens to receive a portion of SushiSwap’s transaction fees.',
    website: 'https://sushi.com/',
  },
  sys: {
    icon: require('cryptocurrency-icons/128/color/sys.png'),
    color: '#0082C6',
    description: '',
    website: '',
  },
  taas: {
    icon: require('cryptocurrency-icons/128/color/taas.png'),
    color: '#002342',
    description: '',
    website: '',
  },
  tau: {
    icon: require('cryptocurrency-icons/128/color/tau.png'),
    color: '#7B346E',
    description: '',
    website: '',
  },
  tbx: {
    icon: require('cryptocurrency-icons/128/color/tbx.png'),
    color: '#5244D4',
    description: '',
    website: '',
  },
  tel: {
    icon: require('cryptocurrency-icons/128/color/tel.png'),
    color: '#14C8FF',
    description: '',
    website: '',
  },
  ten: {
    icon: require('cryptocurrency-icons/128/color/ten.png'),
    color: '#0899CD',
    description: '',
    website: '',
  },
  tern: {
    icon: require('cryptocurrency-icons/128/color/tern.png'),
    color: '#F4C257',
    description: '',
    website: '',
  },
  tgch: {
    icon: require('cryptocurrency-icons/128/color/tgch.png'),
    color: '#434247',
    description: '',
    website: '',
  },
  theta: {
    icon: require('cryptocurrency-icons/128/color/theta.png'),
    color: '#2AB8E6',
    description: '',
    website: '',
  },
  tix: {
    icon: require('cryptocurrency-icons/128/color/tix.png'),
    color: '#EF494D',
    description: '',
    website: '',
  },
  tkn: {
    icon: require('cryptocurrency-icons/128/color/tkn.png'),
    color: '#24DD7B',
    description: '',
    website: '',
  },
  tks: {
    icon: require('cryptocurrency-icons/128/color/tks.png'),
    color: '#895AF8',
    description: '',
    website: '',
  },
  tnb: {
    icon: require('cryptocurrency-icons/128/color/tnb.png'),
    color: '#FFC04E',
    description: '',
    website: '',
  },
  tnc: {
    icon: require('cryptocurrency-icons/128/color/tnc.png'),
    color: '#FF439B',
    description: '',
    website: '',
  },
  tnt: {
    icon: require('cryptocurrency-icons/128/color/tnt.png'),
    color: '#FF4081',
    description: '',
    website: '',
  },
  tomo: {
    icon: require('cryptocurrency-icons/128/color/tomo.png'),
    color: '#1A1F36',
    description: '',
    website: '',
  },
  tpay: {
    icon: require('cryptocurrency-icons/128/color/tpay.png'),
    color: '#3058A6',
    description: '',
    website: '',
  },
  tribe: {
    icon: require('../../assets/cryptos/tribe.png'),
    color: '#178DD0',
    description: 'TRIBE is an Ethereum token that governs Fei Protocol, which issues a separate, decentralized stablecoin called FEI that attempts to maintain a value of US$1.00. TRIBE can be used to vote for Fei Protocol upgrades and to adjust FEI stablecoin monetary policy.',
    website: 'https://fei.money/',
  },
  trig: {
    icon: require('cryptocurrency-icons/128/color/trig.png'),
    color: '#30C0F2',
    description: '',
    website: '',
  },
  trtl: {
    icon: require('cryptocurrency-icons/128/color/trtl.png'),
    color: '#00843D',
    description: '',
    website: '',
  },
  trb: {
    icon: require('../../assets/cryptos/trb.png'),
    color: '#000000',
    description: 'Tellor is a decentralized oracle network that allows smart contracts on Ethereum to securely connect to external data sources. TRB (a.k.a. “Tributes”) is an Ethereum token that powers the Tellor network and incentivizes honest reporting of external data.',
    website: 'https://tellor.io/',
  },
  tru: {
    icon: require('../../assets/cryptos/tru.png'),
    color: '#1A5AFF',
    description: 'TRU is an Ethereum token that powers TrueFi, a decentralized finance protocol for uncollateralized lending using on-chain credit scores. TRU can be used for staking (i.e. to approve or reject new loans) and governance on the TrueFi protocol.',
    website: 'https://truefi.io/',
  },
  trx: {
    icon: require('cryptocurrency-icons/128/color/trx.png'),
    color: '#EF0027',
    description: '',
    website: '',
  },
  tusd: {
    icon: require('cryptocurrency-icons/128/color/tusd.png'),
    color: '#2B2E7F',
    description: '',
    website: '',
  },
  tzc: {
    icon: require('cryptocurrency-icons/128/color/tzc.png'),
    color: '#374851',
    description: '',
    website: '',
  },
  ubq: {
    icon: require('cryptocurrency-icons/128/color/ubq.png'),
    color: '#00EB8F',
    description: '',
    website: '',
  },
  uma: {
    icon: require('cryptocurrency-icons/128/color/uma.png'),
    color: '#FF4A49',
    description: 'UMA is an Ethereum token that describes itself as “an open-source protocol that allows developers to design and create their own financial contracts and synthetic assets.” The protocol’s name comes from the team’s goal of creating universal market access (UMA).',
    website: 'https://umaproject.org/',
  },
  uni: {
    icon: require('cryptocurrency-icons/128/color/uni.png'),
    color: '#FF007A',
    description: 'Uniswap (UNI) is an Ethereum token that powers Uniswap, an automated liquidity provider that’s designed to make it easy to exchange Ethereum (ERC-20) tokens. There is no orderbook or central facilitator on Uniswap. Instead, tokens are exchanged through liquidity pools that are defined by smart contracts.',
    website: 'https://uniswap.org/',
  },
  unity: {
    icon: require('cryptocurrency-icons/128/color/unity.png'),
    color: '#F58634',
    description: '',
    website: '',
  },
  usd: {
    icon: require('cryptocurrency-icons/128/color/usd.png'),
    color: '#6BDE07',
    description: '',
    website: '',
  },
  usdc: {
    icon: require('cryptocurrency-icons/128/color/usdc.png'),
    color: '#2775C9',
    description: 'USD Coin (USDC) is a stablecoin fully backed by the US dollar and developed by the CENTRE consortium. Coinbase customers with US dollar accounts may exchange 1 USDC for US$1.00 (and vice versa) on Coinbase in jurisdictions where USDC support is available. The graph above reflects USDC’s current and historical redemption value of US$1.00, which may not match the price of USDC on other exchanges. USDC is an Ethereum token and is the only fiat-backed stablecoin currently supported by Coinbase. Note: Coinbase only supports USDC running on Ethereum (ERC-20).',
    website: 'https://www.coinbase.com/usdc/',
  },
  usdt: {
    icon: require('cryptocurrency-icons/128/color/usdt.png'),
    color: '#27A17C',
    description: 'Tether (USDT) is an Ethereum token that is pegged to the value of a U.S. dollar (also known as a stablecoin). Tether’s issuer claims that USDT is backed by bank reserves and loans which match or exceed the value of USDT in circulation. Important note: at this time, Coinbase only supports USDT on the Ethereum blockchain (ERC-20). Do not send USDT on any other blockchain to Coinbase.',
    website: 'https://tether.to/',
  },
  ust: {
    icon: require('../../assets/cryptos/ust.png'),
    color: '#5493F7',
    description: 'TerraUSD is a decentralized stablecoin running on Ethereum that attempts to maintain a value of US$1.00. Unlike centralized stablecoins, UST isn’t backed by US dollars in a bank account. Instead, in order to mint 1 TerraUSD, US$1.00 worth of TerraUSD’s reserve asset (LUNA) must be burned.',
    website: 'https://www.terra.money/',
  },
  utk: {
    icon: require('cryptocurrency-icons/128/color/utk.png'),
    color: '#30367A',
    description: '',
    website: '',
  },
  veri: {
    icon: require('cryptocurrency-icons/128/color/veri.png'),
    color: '#FF9933',
    description: '',
    website: '',
  },
  vet: {
    icon: require('cryptocurrency-icons/128/color/vet.png'),
    color: '#15BDFF',
    description: '',
    website: '',
  },
  via: {
    icon: require('cryptocurrency-icons/128/color/via.png'),
    color: '#565656',
    description: '',
    website: '',
  },
  vib: {
    icon: require('cryptocurrency-icons/128/color/vib.png'),
    color: '#FF1F43',
    description: '',
    website: '',
  },
  vibe: {
    icon: require('cryptocurrency-icons/128/color/vibe.png'),
    color: '#338BE5',
    description: '',
    website: '',
  },
  vivo: {
    icon: require('cryptocurrency-icons/128/color/vivo.png'),
    color: '#408AF1',
    description: '',
    website: '',
  },
  vrc: {
    icon: require('cryptocurrency-icons/128/color/vrc.png'),
    color: '#418BCA',
    description: '',
    website: '',
  },
  vrsc: {
    icon: require('cryptocurrency-icons/128/color/vrsc.png'),
    color: '#FFB500',
    description: '',
    website: '',
  },
  vtc: {
    icon: require('cryptocurrency-icons/128/color/vtc.png'),
    color: '#048657',
    description: '',
    website: '',
  },
  vtho: {
    icon: require('cryptocurrency-icons/128/color/vtho.png'),
    color: '#2A5284',
    description: '',
    website: '',
  },
  wabi: {
    icon: require('cryptocurrency-icons/128/color/wabi.png'),
    color: '#3A9B32',
    description: '',
    website: '',
  },
  wan: {
    icon: require('cryptocurrency-icons/128/color/wan.png'),
    color: '#136AAD',
    description: '',
    website: '',
  },
  waves: {
    icon: require('cryptocurrency-icons/128/color/waves.png'),
    color: '#0155FF',
    description: '',
    website: '',
  },
  wax: {
    icon: require('cryptocurrency-icons/128/color/wax.png'),
    color: '#F89022',
    description: '',
    website: '',
  },
  wbtc: {
    icon: require('cryptocurrency-icons/128/color/wbtc.png'),
    color: '#1F1B2C',
    description: 'Wrapped Bitcoin (WBTC) is an Ethereum token that is intended to represent Bitcoin (BTC) on the Ethereum blockchain. It is not Bitcoin, but rather a separate ERC-20 token that’s designed to track Bitcoin’s value. WBTC was created to allow Bitcoin holders to participate in decentralized finance (“DeFi”) apps that are popular on Ethereum. Through a WBTC partner, 1 Bitcoin can be exchanged for 1 Wrapped Bitcoin, and vice-versa. The BTC that backs WBTC is verifiable through a “proof of reserve” system that verifies the 1:1 backing between minted WBTC tokens and Bitcoin stored by custodians. WBTC is maintained by a group called the WBTC DAO that consists of over 30 members. It was originally started by BitGo, Ren, and Kyber.',
    website: 'https://wbtc.network/',
  },
  wgr: {
    icon: require('cryptocurrency-icons/128/color/wgr.png'),
    color: '#B80000',
    description: '',
    website: '',
  },
  wicc: {
    icon: require('cryptocurrency-icons/128/color/wicc.png'),
    color: '#5783CB',
    description: '',
    website: '',
  },
  wings: {
    icon: require('cryptocurrency-icons/128/color/wings.png'),
    color: '#0DC9F7',
    description: '',
    website: '',
  },
  wluna: {
    icon: require('../../assets/cryptos/wluna.png'),
    color: '#F9D85E',
    description: 'Wrapped Luna (WLUNA) is an Ethereum token that’s intended to represent Terra (LUNA) on the Ethereum blockchain. It is not LUNA, but rather a separate ERC-20 token that’s designed to track LUNA’s value. WLUNA was created to allow LUNA holders to trade, hold, and participate in decentralized finance (“DeFi”) apps on Ethereum. Through a WLUNA partner, 1 LUNA can be exchanged for 1 WLUNA, and vice-versa.',
    website: 'https://www.terra.money/',
  },
  wpr: {
    icon: require('cryptocurrency-icons/128/color/wpr.png'),
    color: '#FFE600',
    description: '',
    website: '',
  },
  wtc: {
    icon: require('cryptocurrency-icons/128/color/wtc.png'),
    color: '#8200FF',
    description: '',
    website: '',
  },
  x: {
    icon: require('cryptocurrency-icons/128/color/x.png'),
    color: '#3B5999',
    description: '',
    website: '',
  },
  xas: {
    icon: require('cryptocurrency-icons/128/color/xas.png'),
    color: '#FAA00D',
    description: '',
    website: '',
  },
  xbc: {
    icon: require('cryptocurrency-icons/128/color/xbc.png'),
    color: '#F7931A',
    description: '',
    website: '',
  },
  xbp: {
    icon: require('cryptocurrency-icons/128/color/xbp.png'),
    color: '#21AF67',
    description: '',
    website: '',
  },
  xby: {
    icon: require('cryptocurrency-icons/128/color/xby.png'),
    color: '#56F4F1',
    description: '',
    website: '',
  },
  xcp: {
    icon: require('cryptocurrency-icons/128/color/xcp.png'),
    color: '#ED1650',
    description: '',
    website: '',
  },
  xdn: {
    icon: require('cryptocurrency-icons/128/color/xdn.png'),
    color: '#4F7BA2',
    description: '',
    website: '',
  },
  xem: {
    icon: require('cryptocurrency-icons/128/color/xem.png'),
    color: '#67B2E8',
    description: '',
    website: '',
  },
  xin: {
    icon: require('cryptocurrency-icons/128/color/xin.png'),
    color: '#1EB5FA',
    description: '',
    website: '',
  },
  xlm: {
    icon: require('cryptocurrency-icons/128/color/xlm.png'),
    color: '#000000',
    description: 'Stellar’s cryptocurrency, the Stellar Lumen (XLM), powers the Stellar payment network. Stellar aims to connect banks, payment systems, and individuals quickly and reliably.',
    website: 'https://www.stellar.org/',
  },
  xmcc: {
    icon: require('cryptocurrency-icons/128/color/xmcc.png'),
    color: '#DD0632',
    description: '',
    website: '',
  },
  xmg: {
    icon: require('cryptocurrency-icons/128/color/xmg.png'),
    color: '#004A80',
    description: '',
    website: '',
  },
  xmo: {
    icon: require('cryptocurrency-icons/128/color/xmo.png'),
    color: '#FF6600',
    description: '',
    website: '',
  },
  xmr: {
    icon: require('cryptocurrency-icons/128/color/xmr.png'),
    color: '#FF6600',
    description: '',
    website: '',
  },
  xmy: {
    icon: require('cryptocurrency-icons/128/color/xmy.png'),
    color: '#EC0F76',
    description: '',
    website: '',
  },
  xp: {
    icon: require('cryptocurrency-icons/128/color/xp.png'),
    color: '#008200',
    description: '',
    website: '',
  },
  xpa: {
    icon: require('cryptocurrency-icons/128/color/xpa.png'),
    color: '#4FA784',
    description: '',
    website: '',
  },
  xpm: {
    icon: require('cryptocurrency-icons/128/color/xpm.png'),
    color: '#FFD81B',
    description: '',
    website: '',
  },
  xrp: {
    icon: require('cryptocurrency-icons/128/color/xrp.png'),
    color: '#24292F',
    description: 'In light of the SEC’s action against Ripple Labs, Inc., trading in XRP has been suspended as of January 19, 2021. XRP is the cryptocurrency used by the Ripple payment network. Built for enterprise use, XRP aims to be a fast, cost-efficient cryptocurrency for cross-border payments.',
    website: 'https://ripple.com/xrp/',
  },
  xsg: {
    icon: require('cryptocurrency-icons/128/color/xsg.png'),
    color: '#D21E2B',
    description: '',
    website: '',
  },
  xtz: {
    icon: require('cryptocurrency-icons/128/color/xtz.png'),
    color: '#A6E000',
    description: 'Tezos is a cryptocurrency and decentralized computing platform. Its features include proof of stake consensus, formal verification (which lets developers verify the correctness of their code), and the ability to let stakeholders vote on changes to the protocol. Tezos\'s block creation process is called "baking" — Tezos holders who stake their tokens can receive Tezos tokens as a reward for creating and verifying blocks.',
    website: 'https://www.tezos.com/',
  },
  xuc: {
    icon: require('cryptocurrency-icons/128/color/xuc.png'),
    color: '#25AAE3',
    description: '',
    website: '',
  },
  xvc: {
    icon: require('cryptocurrency-icons/128/color/xvc.png'),
    color: '#B50126',
    description: '',
    website: '',
  },
  xvg: {
    icon: require('cryptocurrency-icons/128/color/xvg.png'),
    color: '#00CBFF',
    description: '',
    website: '',
  },
  xzc: {
    icon: require('cryptocurrency-icons/128/color/xzc.png'),
    color: '#23B852',
    description: '',
    website: '',
  },
  yfi: {
    icon: require('cryptocurrency-icons/128/color/yfi.png'),
    color: '#006AE2',
    description: 'Yearn.finance (YFI) is an Ethereum token that governs the Yearn.finance platform. The platform is a yield optimizer that moves funds around the decentralized finance (“defi”) ecosystem in an effort to generate a high return.',
    website: 'https://yearn.finance/',
  },
  yoyow: {
    icon: require('cryptocurrency-icons/128/color/yoyow.png'),
    color: '#21A5DE',
    description: '',
    website: '',
  },
  zcl: {
    icon: require('cryptocurrency-icons/128/color/zcl.png'),
    color: '#C87035',
    description: '',
    website: '',
  },
  zec: {
    icon: require('cryptocurrency-icons/128/color/zec.png'),
    color: '#ECB244',
    description: 'Zcash is a cryptocurrency that offers two types of addresses: transparent addresses that are publicly visible on the Zcash blockchain and shielded addresses that are more private. Coinbase customers can receive Zcash from both transparent and shielded addresses and send Zcash to transparent addresses. Sending to shielded addresses is not supported at this time.',
    website: 'https://z.cash/',
  },
  zel: {
    icon: require('cryptocurrency-icons/128/color/zel.png'),
    color: '#183C87',
    description: '',
    website: '',
  },
  zen: {
    icon: require('cryptocurrency-icons/128/color/zen.png'),
    color: '#00EAAB',
    description: '',
    website: '',
  },
  zest: {
    icon: require('cryptocurrency-icons/128/color/zest.png'),
    color: '#07BC9C',
    description: '',
    website: '',
  },
  zil: {
    icon: require('cryptocurrency-icons/128/color/zil.png'),
    color: '#49C1BF',
    description: '',
    website: '',
  },
  zilla: {
    icon: require('cryptocurrency-icons/128/color/zilla.png'),
    color: '#00004D',
    description: '',
    website: '',
  },
  zrx: {
    icon: require('cryptocurrency-icons/128/color/zrx.png'),
    color: '#302C2B',
    description: 'ZRX is an Ethereum token that is used to power the 0x protocol. The protocol itself is designed to allow Ethereum tokens to be traded at a low cost directly from your wallet.',
    website: 'https://0x.org/',
  },
};

export default CryptoCurrenciesIconMap;
