
const CryptoCurrenciesIconMap = {
	"$pac": { icon: require('cryptocurrency-icons/128/color/$pac.png'), color: '#F5EB17' , description: '', website: '' },
	"0xbtc": { icon: require('cryptocurrency-icons/128/color/0xbtc.png'), color: '#FF914C' , description: '', website: '' },
	"2give": { icon: require('cryptocurrency-icons/128/color/2give.png'), color: '#F1CB60' , description: '', website: '' },
	"aave": { icon: require('./../../assets/cryptos/aave.png'), color: '#B6509E' , description: 'Aave (AAVE) is an Ethereum token that powers Aave, a decentralized non-custodial money market protocol where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow cryptocurrencies in exchange for paying a variable interest rate.', website: 'https://aave.com/' },
	"abt": { icon: require('cryptocurrency-icons/128/color/abt.png'), color: '#3EFEFF' , description: '', website: '' },
	"act": { icon: require('cryptocurrency-icons/128/color/act.png'), color: '#767DFF' , description: '', website: '' },
	"actn": { icon: require('cryptocurrency-icons/128/color/actn.png'), color: '#FF0000' , description: '', website: '' },
	"ada": { icon: require('cryptocurrency-icons/128/color/ada.png'), color: '#0D1E30' , description: '', website: '' },
	"add": { icon: require('cryptocurrency-icons/128/color/add.png'), color: '#FEC807' , description: '', website: '' },
	"adx": { icon: require('cryptocurrency-icons/128/color/adx.png'), color: '#1B75BC' , description: '', website: '' },
	"ae": { icon: require('cryptocurrency-icons/128/color/ae.png'), color: '#DE3F6B' , description: '', website: '' },
	"aeon": { icon: require('cryptocurrency-icons/128/color/aeon.png'), color: '#134451' , description: '', website: '' },
	"aeur": { icon: require('cryptocurrency-icons/128/color/aeur.png'), color: '#051D2D' , description: '', website: '' },
	"agi": { icon: require('cryptocurrency-icons/128/color/agi.png'), color: '#6916FF' , description: '', website: '' },
	"agrs": { icon: require('cryptocurrency-icons/128/color/agrs.png'), color: '#F49E00' , description: '', website: '' },
	"aion": { icon: require('cryptocurrency-icons/128/color/aion.png'), color: '#00BFEC' , description: '', website: '' },
	"algo": { icon: require('cryptocurrency-icons/128/color/algo.png'), color: '#000000' , description: 'Algorand is a cryptocurrency and blockchain protocol that aims to be simultaneously scalable, secure, and decentralized. It uses a consensus algorithm called pure proof-of-stake.', website: 'https://www.algorand.com/' },
	"amb": { icon: require('cryptocurrency-icons/128/color/amb.png'), color: '#3D5BE1' , description: '', website: '' },
	"amp": { icon: require('cryptocurrency-icons/128/color/amp.png'), color: '#3FB5E6' , description: '', website: '' },
	"ampl": { icon: require('cryptocurrency-icons/128/color/ampl.png'), color: '#000000' , description: '', website: '' },
	"ant": { icon: require('cryptocurrency-icons/128/color/ant.png'), color: '#2CD3E1' , description: '', website: '' },
	"apex": { icon: require('cryptocurrency-icons/128/color/apex.png'), color: '#1F4C9F' , description: '', website: '' },
	"appc": { icon: require('cryptocurrency-icons/128/color/appc.png'), color: '#FD875E' , description: '', website: '' },
	"ardr": { icon: require('cryptocurrency-icons/128/color/ardr.png'), color: '#3C87C7' , description: '', website: '' },
	"arg": { icon: require('cryptocurrency-icons/128/color/arg.png'), color: '#A71435' , description: '', website: '' },
	"ark": { icon: require('cryptocurrency-icons/128/color/ark.png'), color: '#F70000' , description: '', website: '' },
	"arn": { icon: require('cryptocurrency-icons/128/color/arn.png'), color: '#0092B5' , description: '', website: '' },
	"arnx": { icon: require('cryptocurrency-icons/128/color/arnx.png'), color: '#436697' , description: '', website: '' },
	"ary": { icon: require('cryptocurrency-icons/128/color/ary.png'), color: '#343434' , description: '', website: '' },
	"ast": { icon: require('cryptocurrency-icons/128/color/ast.png'), color: '#0061FF' , description: '', website: '' },
	"atm": { icon: require('cryptocurrency-icons/128/color/atm.png'), color: '#346FCD' , description: '', website: '' },
	"atom": { icon: require('cryptocurrency-icons/128/color/atom.png'), color: '#2F3148' , description: 'Cosmos (ATOM) is a cryptocurrency that powers an ecosystem of blockchains designed to scale and interoperate with each other. The team aims to "create an Internet of Blockchains, a network of blockchains able to communicate with each other in a decentralized way." Cosmos is a proof-of-stake chain. ATOM holders can stake their tokens in order to maintain the network and receive more ATOM as a reward.', website: 'https://cosmos.network/' },
	"audr": { icon: require('cryptocurrency-icons/128/color/audr.png'), color: '#34318A' , description: '', website: '' },
	"auto": { icon: require('cryptocurrency-icons/128/color/auto.png'), color: '#FAB431' , description: '', website: '' },
	"aywa": { icon: require('cryptocurrency-icons/128/color/aywa.png'), color: '#3355B5' , description: '', website: '' },
	"bab": { icon: require('cryptocurrency-icons/128/color/bab.png'), color: '#F1A013' , description: '', website: '' },
	"bal": { icon: require('cryptocurrency-icons/128/color/bal.png'), color: '#1E1E1E' , description: 'Balancer (BAL) is an Ethereum token that powers the Balancer protocol, an automated market maker that lets anyone create or add liquidity to trading pools while earning customizable trading fees. Balancer pools can have up to 8 tokens and each token can be individually weighted within the pool, such that one token can make up as little as 2% of the total.', website: 'https://balancer.finance/' },
	"band": { icon: require('cryptocurrency-icons/128/color/band.png'), color: '#516BFF' , description: 'Band is a cryptocurrency that describes itself as “a cross-chain data oracle platform that aggregates and connects real-world data and APIs to smart contracts.” Band allows blockchains to access data, such as stock prices and weather, that are available via API. Note: Coinbase only supports the Band token running on Ethereum (ERC-20).', website: 'https://bandprotocol.com/' },
	"bat": { icon: require('cryptocurrency-icons/128/color/bat.png'), color: '#FF5000' , description: 'BAT is an Ethereum token that powers Brave Software\'s blockchain-based digital advertising platform. Internet users who browse the web using Brave\'s free web browser (available at Brave.com) can choose to replace the ads they see with ads on Brave\'s ad network. Users then receive BAT from advertisers as compensation for their attention.', website: 'https://basicattentiontoken.org/' },
	"bay": { icon: require('cryptocurrency-icons/128/color/bay.png'), color: '#6356AB' , description: '', website: '' },
	"bcbc": { icon: require('cryptocurrency-icons/128/color/bcbc.png'), color: '#004AB5' , description: '', website: '' },
	"bcc": { icon: require('cryptocurrency-icons/128/color/bcc.png'), color: '#F7931C' , description: '', website: '' },
	"bcd": { icon: require('cryptocurrency-icons/128/color/bcd.png'), color: '#FCC339' , description: '', website: '' },
	"bch": { icon: require('cryptocurrency-icons/128/color/bch.png'), color: '#8DC351' , description: 'Bitcoin Cash is a fork of Bitcoin that seeks to add more transaction capacity to the network in order to be useful for everyday transactions.', website: 'http://bch.info/' },
	"bcio": { icon: require('cryptocurrency-icons/128/color/bcio.png'), color: '#3F43AD' , description: '', website: '' },
	"bcn": { icon: require('cryptocurrency-icons/128/color/bcn.png'), color: '#F04086' , description: '', website: '' },
	"bco": { icon: require('cryptocurrency-icons/128/color/bco.png'), color: '#2C76B7' , description: '', website: '' },
	"bcpt": { icon: require('cryptocurrency-icons/128/color/bcpt.png'), color: '#404040' , description: '', website: '' },
	"bdl": { icon: require('cryptocurrency-icons/128/color/bdl.png'), color: '#E54C40' , description: '', website: '' },
	"beam": { icon: require('cryptocurrency-icons/128/color/beam.png'), color: '#0B76FF' , description: '', website: '' },
	"bela": { icon: require('cryptocurrency-icons/128/color/bela.png'), color: '#13A0F6' , description: '', website: '' },
	"bix": { icon: require('cryptocurrency-icons/128/color/bix.png'), color: '#000000' , description: '', website: '' },
	"blcn": { icon: require('cryptocurrency-icons/128/color/blcn.png'), color: '#2AABE4' , description: '', website: '' },
	"blk": { icon: require('cryptocurrency-icons/128/color/blk.png'), color: '#181818' , description: '', website: '' },
	"block": { icon: require('cryptocurrency-icons/128/color/block.png'), color: '#101341' , description: '', website: '' },
	"blz": { icon: require('cryptocurrency-icons/128/color/blz.png'), color: '#18578C' , description: '', website: '' },
	"bnb": { icon: require('cryptocurrency-icons/128/color/bnb.png'), color: '#F3BA2F' , description: '', website: '' },
	"bnt": { icon: require('cryptocurrency-icons/128/color/bnt.png'), color: '#000E2B' , description: 'Bancor Network Token (BNT) is an Ethereum token that powers the Bancor protocol. The protocol describes itself as “a fully on-chain liquidity protocol that can be implemented on any smart contract-enabled blockchain.”', website: 'https://bancor.network/' },
	"bnty": { icon: require('cryptocurrency-icons/128/color/bnty.png'), color: '#FD7A3D' , description: '', website: '' },
	"booty": { icon: require('cryptocurrency-icons/128/color/booty.png'), color: '#00B4F4' , description: '', website: '' },
	"bos": { icon: require('cryptocurrency-icons/128/color/bos.png'), color: '#00A8D6' , description: '', website: '' },
	"bpt": { icon: require('cryptocurrency-icons/128/color/bpt.png'), color: '#0F63D8' , description: '', website: '' },
	"bq": { icon: require('cryptocurrency-icons/128/color/bq.png'), color: '#1D1D1D' , description: '', website: '' },
	"brd": { icon: require('cryptocurrency-icons/128/color/brd.png'), color: '#FE5D86' , description: '', website: '' },
	"bsd": { icon: require('cryptocurrency-icons/128/color/bsd.png'), color: '#000000' , description: '', website: '' },
	"bsv": { icon: require('cryptocurrency-icons/128/color/bsv.png'), color: '#EAB304' , description: '', website: '' },
	"btc": { icon: require('cryptocurrency-icons/128/color/btc.png'), color: '#F7931B' , description: 'The world’s first cryptocurrency, Bitcoin is stored and exchanged securely on the internet through a digital ledger known as a blockchain. Bitcoins are divisible into smaller units known as satoshis — each satoshi is worth 0.00000001 bitcoin.', website: 'https://bitcoin.org/' },
	"btcd": { icon: require('cryptocurrency-icons/128/color/btcd.png'), color: '#FF6600' , description: '', website: '' },
	"btch": { icon: require('cryptocurrency-icons/128/color/btch.png'), color: '#4700C2' , description: '', website: '' },
	"btcp": { icon: require('cryptocurrency-icons/128/color/btcp.png'), color: '#272D63' , description: '', website: '' },
	"btcz": { icon: require('cryptocurrency-icons/128/color/btcz.png'), color: '#F8C24A' , description: '', website: '' },
	"btdx": { icon: require('cryptocurrency-icons/128/color/btdx.png'), color: '#00AAFF' , description: '', website: '' },
	"btg": { icon: require('cryptocurrency-icons/128/color/btg.png'), color: '#EBA809' , description: '', website: '' },
	"btm": { icon: require('cryptocurrency-icons/128/color/btm.png'), color: '#504C4C' , description: '', website: '' },
	"bts": { icon: require('cryptocurrency-icons/128/color/bts.png'), color: '#35BAEB' , description: '', website: '' },
	"btt": { icon: require('cryptocurrency-icons/128/color/btt.png'), color: '#000000' , description: '', website: '' },
	"btx": { icon: require('cryptocurrency-icons/128/color/btx.png'), color: '#ED309C' , description: '', website: '' },
	"burst": { icon: require('cryptocurrency-icons/128/color/burst.png'), color: '#2D2D2D' , description: '', website: '' },
	"bze": { icon: require('cryptocurrency-icons/128/color/bze.png'), color: '#00AEEF' , description: '', website: '' },
	"call": { icon: require('cryptocurrency-icons/128/color/call.png'), color: '#FCB414' , description: '', website: '' },
	"cc": { icon: require('cryptocurrency-icons/128/color/cc.png'), color: '#36B0F3' , description: '', website: '' },
	"cdn": { icon: require('cryptocurrency-icons/128/color/cdn.png'), color: '#F70808' , description: '', website: '' },
	"cdt": { icon: require('cryptocurrency-icons/128/color/cdt.png'), color: '#272731' , description: '', website: '' },
	"cenz": { icon: require('cryptocurrency-icons/128/color/cenz.png'), color: '#3088F2' , description: '', website: '' },
	"cgld": { icon: require('./../../assets/cryptos/cgld.png'), color: '#FBCC5C' , description: 'Celo is the core utility, reserve, staking, and governance asset for the Celo platform. The platform aims to make financial tools borderless, easy to use, and accessible for anyone with a mobile phone.', website: 'https://celo.org/' },
	"chain": { icon: require('cryptocurrency-icons/128/color/chain.png'), color: '#00ACED' , description: '', website: '' },
	"chat": { icon: require('cryptocurrency-icons/128/color/chat.png'), color: '#1C98F7' , description: '', website: '' },
	"chips": { icon: require('cryptocurrency-icons/128/color/chips.png'), color: '#598182' , description: '', website: '' },
	"cix": { icon: require('cryptocurrency-icons/128/color/cix.png'), color: '#0576B4' , description: '', website: '' },
	"clam": { icon: require('cryptocurrency-icons/128/color/clam.png'), color: '#20C5D3' , description: '', website: '' },
	"cloak": { icon: require('cryptocurrency-icons/128/color/cloak.png'), color: '#FF3A00' , description: '', website: '' },
	"cmm": { icon: require('cryptocurrency-icons/128/color/cmm.png'), color: '#2FD2E5' , description: '', website: '' },
	"cmt": { icon: require('cryptocurrency-icons/128/color/cmt.png'), color: '#C1A05C' , description: '', website: '' },
	"cnd": { icon: require('cryptocurrency-icons/128/color/cnd.png'), color: '#383939' , description: '', website: '' },
	"cnx": { icon: require('cryptocurrency-icons/128/color/cnx.png'), color: '#4C6BAE' , description: '', website: '' },
	"cny": { icon: require('cryptocurrency-icons/128/color/cny.png'), color: '#FF4315' , description: '', website: '' },
	"cob": { icon: require('cryptocurrency-icons/128/color/cob.png'), color: '#13BF99' , description: '', website: '' },
	"colx": { icon: require('cryptocurrency-icons/128/color/colx.png'), color: '#77C3B0' , description: '', website: '' },
	"comp": { icon: require('cryptocurrency-icons/128/color/comp.png'), color: '#01D396' , description: 'Compound (COMP) is an Ethereum token that enables community governance of the Compound protocol. The protocol is a series of decentralized interest rate markets that allow users to supply and borrow Ethereum tokens at variable interest rates. COMP token holders and their delegates can also debate, propose, and vote on changes to the protocol.', website: 'https://compound.finance/' },
	"coqui": { icon: require('cryptocurrency-icons/128/color/coqui.png'), color: '#71C800' , description: '', website: '' },
	"cred": { icon: require('cryptocurrency-icons/128/color/cred.png'), color: '#37E8A3' , description: '', website: '' },
	"crpt": { icon: require('cryptocurrency-icons/128/color/crpt.png'), color: '#189AA5' , description: '', website: '' },
	"crw": { icon: require('cryptocurrency-icons/128/color/crw.png'), color: '#0F1529' , description: '', website: '' },
	"cs": { icon: require('cryptocurrency-icons/128/color/cs.png'), color: '#262626' , description: '', website: '' },
	"ctr": { icon: require('cryptocurrency-icons/128/color/ctr.png'), color: '#FDDE6C' , description: '', website: '' },
	"ctxc": { icon: require('cryptocurrency-icons/128/color/ctxc.png'), color: '#000000' , description: '', website: '' },
	"cvc": { icon: require('cryptocurrency-icons/128/color/cvc.png'), color: '#3AB03E' , description: 'Civic (CVC) is an Ethereum token used to power Civic’s identity verification protocol. Users who verify their information through Civic can then securely share both their info and the verification with service providers, reducing the need to constantly re-verify their identity. In return for this convenience, service providers may provide users and verifiers with CVC.', website: 'https://www.civic.com/' },
	"d": { icon: require('cryptocurrency-icons/128/color/d.png'), color: '#B8B8B8' , description: '', website: '' },
	"dai": { icon: require('cryptocurrency-icons/128/color/dai.png'), color: '#F3B732' , description: 'Dai (DAI) is a decentralized stablecoin running on Ethereum (ETH) that attempts to maintain a value of $1.00 USD. Unlike centralized stablecoins, Dai isn\'t backed by US dollars in a bank account. Instead, it’s backed by collateral on the Maker platform. Note: if the Dai credit system is upgraded or shutdown, Dai holders may need to convert their Dai to Ethereum through the Maker platform. Read more at makerdao.com/whitepaper.', website: 'https://www.makerdao.com/' },
	"dash": { icon: require('cryptocurrency-icons/128/color/dash.png'), color: '#018CE7' , description: 'Dash is a cryptocurrency with optional speed and privacy features. Its unique network architecture consists of both regular miners and privileged machines called Masternodes.', website: 'https://www.dash.org/' },
	"dat": { icon: require('cryptocurrency-icons/128/color/dat.png'), color: '#2D9CDB' , description: '', website: '' },
	"data": { icon: require('cryptocurrency-icons/128/color/data.png'), color: '#E9570F' , description: '', website: '' },
	"dbc": { icon: require('cryptocurrency-icons/128/color/dbc.png'), color: '#5BC1D4' , description: '', website: '' },
	"dcn": { icon: require('cryptocurrency-icons/128/color/dcn.png'), color: '#136485' , description: '', website: '' },
	"dcr": { icon: require('cryptocurrency-icons/128/color/dcr.png'), color: '#2ED6A1' , description: '', website: '' },
	"deez": { icon: require('cryptocurrency-icons/128/color/deez.png'), color: '#939393' , description: '', website: '' },
	"dent": { icon: require('cryptocurrency-icons/128/color/dent.png'), color: '#666666' , description: '', website: '' },
	"dew": { icon: require('cryptocurrency-icons/128/color/dew.png'), color: '#FEC907' , description: '', website: '' },
	"dgb": { icon: require('cryptocurrency-icons/128/color/dgb.png'), color: '#006AD2' , description: '', website: '' },
	"dgd": { icon: require('cryptocurrency-icons/128/color/dgd.png'), color: '#F4D029' , description: '', website: '' },
	"dlt": { icon: require('cryptocurrency-icons/128/color/dlt.png'), color: '#F4AE95' , description: '', website: '' },
	"dnt": { icon: require('cryptocurrency-icons/128/color/dnt.png'), color: '#2D398F' , description: 'District0x is an Ethereum token that powers a network of decentralized marketplaces and communities called districts. The token is required for application to the District Registry and is used to signal support or disapproval for proposals made by network participants.', website: 'https://district0x.io/' },
	"dock": { icon: require('cryptocurrency-icons/128/color/dock.png'), color: '#786DBC' , description: '', website: '' },
	"doge": { icon: require('cryptocurrency-icons/128/color/doge.png'), color: '#C4A634' , description: '', website: '' },
	"dot": { icon: require('cryptocurrency-icons/128/color/dot.png'), color: '#E6007A' , description: '', website: '' },
	"drgn": { icon: require('cryptocurrency-icons/128/color/drgn.png'), color: '#C91111' , description: '', website: '' },
	"drop": { icon: require('cryptocurrency-icons/128/color/drop.png'), color: '#242D3D' , description: '', website: '' },
	"dta": { icon: require('cryptocurrency-icons/128/color/dta.png'), color: '#74D269' , description: '', website: '' },
	"dth": { icon: require('cryptocurrency-icons/128/color/dth.png'), color: '#3C80F1' , description: '', website: '' },
	"dtr": { icon: require('cryptocurrency-icons/128/color/dtr.png'), color: '#121747' , description: '', website: '' },
	"ebst": { icon: require('cryptocurrency-icons/128/color/ebst.png'), color: '#1693D4' , description: '', website: '' },
	"eca": { icon: require('cryptocurrency-icons/128/color/eca.png'), color: '#AA15DD' , description: '', website: '' },
	"edg": { icon: require('cryptocurrency-icons/128/color/edg.png'), color: '#2B1544' , description: '', website: '' },
	"edo": { icon: require('cryptocurrency-icons/128/color/edo.png'), color: '#242424' , description: '', website: '' },
	"edoge": { icon: require('cryptocurrency-icons/128/color/edoge.png'), color: '#0FACF3' , description: '', website: '' },
	"ela": { icon: require('cryptocurrency-icons/128/color/ela.png'), color: '#3FBADF' , description: '', website: '' },
	"elec": { icon: require('cryptocurrency-icons/128/color/elec.png'), color: '#FF9900' , description: '', website: '' },
	"elf": { icon: require('cryptocurrency-icons/128/color/elf.png'), color: '#2B5EBB' , description: '', website: '' },
	"elix": { icon: require('cryptocurrency-icons/128/color/elix.png'), color: '#00ADED' , description: '', website: '' },
	"ella": { icon: require('cryptocurrency-icons/128/color/ella.png'), color: '#396A28' , description: '', website: '' },
	"emc": { icon: require('cryptocurrency-icons/128/color/emc.png'), color: '#B49FFC' , description: '', website: '' },
	"emc2": { icon: require('cryptocurrency-icons/128/color/emc2.png'), color: '#00CCFF' , description: '', website: '' },
	"eng": { icon: require('cryptocurrency-icons/128/color/eng.png'), color: '#2F2F2F' , description: '', website: '' },
	"enj": { icon: require('cryptocurrency-icons/128/color/enj.png'), color: '#614DBE' , description: '', website: '' },
	"entrp": { icon: require('cryptocurrency-icons/128/color/entrp.png'), color: '#FA5836' , description: '', website: '' },
	"eon": { icon: require('cryptocurrency-icons/128/color/eon.png'), color: '#443F54' , description: '', website: '' },
	"eop": { icon: require('cryptocurrency-icons/128/color/eop.png'), color: '#35A7DF' , description: '', website: '' },
	"eos": { icon: require('cryptocurrency-icons/128/color/eos.png'), color: '#000000' , description: 'EOS is a cryptocurrency designed to support large-scale applications. There are no fees to send or receive EOS. Instead, the protocol rewards the entities that run the network periodically with new EOS, effectively substituting inflation for transaction fees.', website: 'https://eos.io/' },
	"eqli": { icon: require('cryptocurrency-icons/128/color/eqli.png'), color: '#C9A35E' , description: '', website: '' },
	"equa": { icon: require('cryptocurrency-icons/128/color/equa.png'), color: '#F68922' , description: '', website: '' },
	"etc": { icon: require('cryptocurrency-icons/128/color/etc.png'), color: '#328432' , description: 'Ethereum Classic is a cryptocurrency with a special focus on immutability, popularly expressed as “code is law.”', website: 'https://ethereumclassic.org/' },
	"eth": { icon: require('cryptocurrency-icons/128/color/eth.png'), color: '#627EEB' , description: 'Ethereum is a decentralized computing platform that uses ETH (also called Ether) to pay transaction fees (or “gas”). Developers can use Ethereum to run decentralized applications (dApps) and issue new crypto assets, known as Ethereum tokens.', website: 'https://ethereum.org/' },
	"ethos": { icon: require('cryptocurrency-icons/128/color/ethos.png'), color: '#00FFBA' , description: '', website: '' },
	"etn": { icon: require('cryptocurrency-icons/128/color/etn.png'), color: '#24BEE2' , description: '', website: '' },
	"etp": { icon: require('cryptocurrency-icons/128/color/etp.png'), color: '#00A5FF' , description: '', website: '' },
	"eur": { icon: require('cryptocurrency-icons/128/color/eur.png'), color: '#0F8FF8' , description: '', website: '' },
	"evx": { icon: require('cryptocurrency-icons/128/color/evx.png'), color: '#044AAC' , description: '', website: '' },
	"exmo": { icon: require('cryptocurrency-icons/128/color/exmo.png'), color: '#347FFB' , description: '', website: '' },
	"exp": { icon: require('cryptocurrency-icons/128/color/exp.png'), color: '#FFAA5C' , description: '', website: '' },
	"fair": { icon: require('cryptocurrency-icons/128/color/fair.png'), color: '#C99705' , description: '', website: '' },
	"fct": { icon: require('cryptocurrency-icons/128/color/fct.png'), color: '#417BA4' , description: '', website: '' },
	"fil": { icon: require('cryptocurrency-icons/128/color/fil.png'), color: '#42C1CA' , description: 'Filecoin (FIL) is a cryptocurrency that powers the Filecoin network, a decentralized peer-to-peer file storage network that aims to let anyone store, retrieve, and host digital information. FIL tokens are used as payment for these services and as an economic incentive to ensure files are stored reliably over time.', website: 'https://filecoin.io/' },
	"fjc": { icon: require('cryptocurrency-icons/128/color/fjc.png'), color: '#00AFEC' , description: '', website: '' },
	"fldc": { icon: require('cryptocurrency-icons/128/color/fldc.png'), color: '#C40E09' , description: '', website: '' },
	"flo": { icon: require('cryptocurrency-icons/128/color/flo.png'), color: '#2080A2' , description: '', website: '' },
	"fsn": { icon: require('cryptocurrency-icons/128/color/fsn.png'), color: '#1D9AD7' , description: '', website: '' },
	"ftc": { icon: require('cryptocurrency-icons/128/color/ftc.png'), color: '#27323A' , description: '', website: '' },
	"fuel": { icon: require('cryptocurrency-icons/128/color/fuel.png'), color: '#4096D0' , description: '', website: '' },
	"fun": { icon: require('cryptocurrency-icons/128/color/fun.png'), color: '#ED1968' , description: '', website: '' },
	"game": { icon: require('cryptocurrency-icons/128/color/game.png'), color: '#2D485B' , description: '', website: '' },
	"gas": { icon: require('cryptocurrency-icons/128/color/gas.png'), color: '#58BF00' , description: '', website: '' },
	"gbp": { icon: require('cryptocurrency-icons/128/color/gbp.png'), color: '#BC3FE0' , description: '', website: '' },
	"gbx": { icon: require('cryptocurrency-icons/128/color/gbx.png'), color: '#1666AF' , description: '', website: '' },
	"gbyte": { icon: require('cryptocurrency-icons/128/color/gbyte.png'), color: '#302C2C' , description: '', website: '' },
	"generic": { icon: require('cryptocurrency-icons/128/color/generic.png'), color: '#EFB914' , description: '', website: '' },
	"gin": { icon: require('cryptocurrency-icons/128/color/gin.png'), color: '#008DDE' , description: '', website: '' },
	"glxt": { icon: require('cryptocurrency-icons/128/color/glxt.png'), color: '#005396' , description: '', website: '' },
	"gmr": { icon: require('cryptocurrency-icons/128/color/gmr.png'), color: '#372D2C' , description: '', website: '' },
	"gno": { icon: require('cryptocurrency-icons/128/color/gno.png'), color: '#00A6C4' , description: '', website: '' },
	"gnt": { icon: require('cryptocurrency-icons/128/color/gnt.png'), color: '#001D57' , description: 'Golem is an Ethereum token that allows users to pay or receive payment for resources via the Golem protocol. The protocol aims to allow participants in the network to loan out their computer’s spare processing power to others.', website: 'https://golem.network/' },
	"gold": { icon: require('cryptocurrency-icons/128/color/gold.png'), color: '#F1B32B' , description: '', website: '' },
	"grc": { icon: require('cryptocurrency-icons/128/color/grc.png'), color: '#5412B4' , description: '', website: '' },
	"grin": { icon: require('cryptocurrency-icons/128/color/grin.png'), color: '#FFF300' , description: '', website: '' },
	"grs": { icon: require('cryptocurrency-icons/128/color/grs.png'), color: '#377E96' , description: '', website: '' },
	"grt": { icon: require('./../../assets/cryptos/grt.png'), color: '#6747ED' , description: 'The Graph (GRT) is an Ethereum token that powers The Graph, a decentralized protocol for indexing and querying data from blockchains. Just as Google indexes the web, The Graph indexes blockchain data from networks like Ethereum and Filecoin. This data is grouped into open APIs called subgraphs that anyone can query.', website: 'https://thegraph.com/' },
	"gsc": { icon: require('cryptocurrency-icons/128/color/gsc.png'), color: '#FF0060' , description: '', website: '' },
	"gto": { icon: require('cryptocurrency-icons/128/color/gto.png'), color: '#7F27FF' , description: '', website: '' },
	"gup": { icon: require('cryptocurrency-icons/128/color/gup.png'), color: '#37DCD8' , description: '', website: '' },
	"gusd": { icon: require('cryptocurrency-icons/128/color/gusd.png'), color: '#00DCFA' , description: '', website: '' },
	"gvt": { icon: require('cryptocurrency-icons/128/color/gvt.png'), color: '#16B9AD' , description: '', website: '' },
	"gxs": { icon: require('cryptocurrency-icons/128/color/gxs.png'), color: '#35A5F3' , description: '', website: '' },
	"gzr": { icon: require('cryptocurrency-icons/128/color/gzr.png'), color: '#56C9E9' , description: '', website: '' },
	"hight": { icon: require('cryptocurrency-icons/128/color/hight.png'), color: '#117FC0' , description: '', website: '' },
	"hodl": { icon: require('cryptocurrency-icons/128/color/hodl.png'), color: '#D59143' , description: '', website: '' },
	"hot": { icon: require('cryptocurrency-icons/128/color/hot.png'), color: '#8734FE' , description: '', website: '' },
	"hpb": { icon: require('cryptocurrency-icons/128/color/hpb.png'), color: '#1591CA' , description: '', website: '' },
	"hsr": { icon: require('cryptocurrency-icons/128/color/hsr.png'), color: '#56428E' , description: '', website: '' },
	"ht": { icon: require('cryptocurrency-icons/128/color/ht.png'), color: '#2A3069' , description: '', website: '' },
	"html": { icon: require('cryptocurrency-icons/128/color/html.png'), color: '#CFA967' , description: '', website: '' },
	"huc": { icon: require('cryptocurrency-icons/128/color/huc.png'), color: '#FFC018' , description: '', website: '' },
	"hush": { icon: require('cryptocurrency-icons/128/color/hush.png'), color: '#292929' , description: '', website: '' },
	"icn": { icon: require('cryptocurrency-icons/128/color/icn.png'), color: '#4C6F8C' , description: '', website: '' },
	"icx": { icon: require('cryptocurrency-icons/128/color/icx.png'), color: '#1FC5C9' , description: '', website: '' },
	"ignis": { icon: require('cryptocurrency-icons/128/color/ignis.png'), color: '#F9C011' , description: '', website: '' },
	"ilk": { icon: require('cryptocurrency-icons/128/color/ilk.png'), color: '#98C23A' , description: '', website: '' },
	"ink": { icon: require('cryptocurrency-icons/128/color/ink.png'), color: '#DF1A14' , description: '', website: '' },
	"ins": { icon: require('cryptocurrency-icons/128/color/ins.png'), color: '#B2A3F6' , description: '', website: '' },
	"ion": { icon: require('cryptocurrency-icons/128/color/ion.png'), color: '#57BEEA' , description: '', website: '' },
	"iop": { icon: require('cryptocurrency-icons/128/color/iop.png'), color: '#0CAFA5' , description: '', website: '' },
	"iost": { icon: require('cryptocurrency-icons/128/color/iost.png'), color: '#1C1C1C' , description: '', website: '' },
	"iotx": { icon: require('cryptocurrency-icons/128/color/iotx.png'), color: '#00D4D5' , description: '', website: '' },
	"iq": { icon: require('cryptocurrency-icons/128/color/iq.png'), color: '#55DDFF' , description: '', website: '' },
	"itc": { icon: require('cryptocurrency-icons/128/color/itc.png'), color: '#102044' , description: '', website: '' },
	"jnt": { icon: require('cryptocurrency-icons/128/color/jnt.png'), color: '#0050DB' , description: '', website: '' },
	"jpy": { icon: require('cryptocurrency-icons/128/color/jpy.png'), color: '#EAC749' , description: '', website: '' },
	"kcs": { icon: require('cryptocurrency-icons/128/color/kcs.png'), color: '#0093DD' , description: '', website: '' },
	"kin": { icon: require('cryptocurrency-icons/128/color/kin.png'), color: '#005FFF' , description: '', website: '' },
	"klown": { icon: require('cryptocurrency-icons/128/color/klown.png'), color: '#EA0017' , description: '', website: '' },
	"kmd": { icon: require('cryptocurrency-icons/128/color/kmd.png'), color: '#2B6680' , description: '', website: '' },
	"knc": { icon: require('cryptocurrency-icons/128/color/knc.png'), color: '#198C93' , description: 'KNC is an Ethereum token used for paying fees on the Kyber Network, a protocol that aims to make swapping digital assets and cryptocurrencies simple and efficient.', website: 'https://kyber.network/' },
	"krb": { icon: require('cryptocurrency-icons/128/color/krb.png'), color: '#00AEEF' , description: '', website: '' },
	"lbc": { icon: require('cryptocurrency-icons/128/color/lbc.png'), color: '#006148' , description: '', website: '' },
	"lend": { icon: require('cryptocurrency-icons/128/color/lend.png'), color: '#0FA9C9' , description: '', website: '' },
	"leo": { icon: require('cryptocurrency-icons/128/color/leo.png'), color: '#11021E' , description: '', website: '' },
	"link": { icon: require('cryptocurrency-icons/128/color/link.png'), color: '#2A5ADA' , description: 'Chainlink (LINK) is an Ethereum token that powers the Chainlink decentralized oracle network. This network allows smart contracts on Ethereum to securely connect to external data sources, APIs, and payment systems.', website: 'https://chain.link/' },
	"lkk": { icon: require('cryptocurrency-icons/128/color/lkk.png'), color: '#9D01EB' , description: '', website: '' },
	"loom": { icon: require('cryptocurrency-icons/128/color/loom.png'), color: '#48BEFE' , description: 'Loom Network (LOOM) is an Ethereum token that powers a network of delegated proof of stake sidechains (a system that Loom dubs “EOS on Ethereum”). This allows for highly-scalable games and user-facing dApps backed by the security of Ethereum.', website: 'https://loomx.io/' },
	"lpt": { icon: require('cryptocurrency-icons/128/color/lpt.png'), color: '#000000' , description: '', website: '' },
	"lrc": { icon: require('cryptocurrency-icons/128/color/lrc.png'), color: '#2AB5F6' , description: 'Loopring is an Ethereum token that describes itself as “an open-sourced, audited, and non-custodial exchange protocol.” It aims to allow anyone to build non-custodial, order book-based exchanges on Ethereum by leveraging zero-knowledge proofs.', website: 'https://loopring.org/' },
	"lsk": { icon: require('cryptocurrency-icons/128/color/lsk.png'), color: '#0D4EA0' , description: '', website: '' },
	"ltc": { icon: require('cryptocurrency-icons/128/color/ltc.png'), color: '#BFBBBB' , description: 'Litecoin is a cryptocurrency that uses a faster payment confirmation schedule and a different cryptographic algorithm than Bitcoin.', website: 'https://litecoin.org/' },
	"lun": { icon: require('cryptocurrency-icons/128/color/lun.png'), color: '#F55749' , description: '', website: '' },
	"maid": { icon: require('cryptocurrency-icons/128/color/maid.png'), color: '#5692D8' , description: '', website: '' },
	"mana": { icon: require('cryptocurrency-icons/128/color/mana.png'), color: '#FF2C55' , description: 'Decentraland (MANA) is an Ethereum token that powers the Decentraland virtual reality platform. MANA can be used to pay for virtual plots of land in Decentraland as well as in-world goods and services.', website: 'https://decentraland.org/' },
	"matic": { icon: require('cryptocurrency-icons/128/color/matic.png'), color: '#2B6DEF' , description: '', website: '' },
	"mcap": { icon: require('cryptocurrency-icons/128/color/mcap.png'), color: '#033B4A' , description: '', website: '' },
	"mco": { icon: require('cryptocurrency-icons/128/color/mco.png'), color: '#103F68' , description: '', website: '' },
	"mda": { icon: require('cryptocurrency-icons/128/color/mda.png'), color: '#01A64F' , description: '', website: '' },
	"mds": { icon: require('cryptocurrency-icons/128/color/mds.png'), color: '#1E252C' , description: '', website: '' },
	"med": { icon: require('cryptocurrency-icons/128/color/med.png'), color: '#00B0FF' , description: '', website: '' },
	"meetone": { icon: require('cryptocurrency-icons/128/color/meetone.png'), color: '#000000' , description: '', website: '' },
	"mft": { icon: require('cryptocurrency-icons/128/color/mft.png'), color: '#DA1157' , description: '', website: '' },
	"miota": { icon: require('cryptocurrency-icons/128/color/miota.png'), color: '#242424' , description: '', website: '' },
	"mith": { icon: require('cryptocurrency-icons/128/color/mith.png'), color: '#00316D' , description: '', website: '' },
	"mkr": { icon: require('cryptocurrency-icons/128/color/mkr.png'), color: '#1AAB9B' , description: 'Maker is an Ethereum token that describes itself as “a utility token, governance token, and recapitalization resource of the Maker system.” The purpose of the Maker system is to generate another Ethereum token, called Dai, that seeks to trade on exchanges at a value of exactly US$1.00.', website: 'https://makerdao.com/' },
	"mln": { icon: require('cryptocurrency-icons/128/color/mln.png'), color: '#0B1529' , description: '', website: '' },
	"mnx": { icon: require('cryptocurrency-icons/128/color/mnx.png'), color: '#00ADEF' , description: '', website: '' },
	"mnz": { icon: require('cryptocurrency-icons/128/color/mnz.png'), color: '#7F368A' , description: '', website: '' },
	"moac": { icon: require('cryptocurrency-icons/128/color/moac.png'), color: '#000000' , description: '', website: '' },
	"mod": { icon: require('cryptocurrency-icons/128/color/mod.png'), color: '#09547D' , description: '', website: '' },
	"mona": { icon: require('cryptocurrency-icons/128/color/mona.png'), color: '#DEC799' , description: '', website: '' },
	"msr": { icon: require('cryptocurrency-icons/128/color/msr.png'), color: '#47B85C' , description: '', website: '' },
	"mth": { icon: require('cryptocurrency-icons/128/color/mth.png'), color: '#104FCA' , description: '', website: '' },
	"mtl": { icon: require('cryptocurrency-icons/128/color/mtl.png'), color: '#1E1F25' , description: '', website: '' },
	"music": { icon: require('cryptocurrency-icons/128/color/music.png'), color: '#FBBF02' , description: '', website: '' },
	"mzc": { icon: require('cryptocurrency-icons/128/color/mzc.png'), color: '#FFAA05' , description: '', website: '' },
	"nano": { icon: require('cryptocurrency-icons/128/color/nano.png'), color: '#4A90E2' , description: '', website: '' },
	"nas": { icon: require('cryptocurrency-icons/128/color/nas.png'), color: '#222222' , description: '', website: '' },
	"nav": { icon: require('cryptocurrency-icons/128/color/nav.png'), color: '#7D59B5' , description: '', website: '' },
	"ncash": { icon: require('cryptocurrency-icons/128/color/ncash.png'), color: '#36A9CF' , description: '', website: '' },
	"ndz": { icon: require('cryptocurrency-icons/128/color/ndz.png'), color: '#622FBA' , description: '', website: '' },
	"nebl": { icon: require('cryptocurrency-icons/128/color/nebl.png'), color: '#50479E' , description: '', website: '' },
	"neo": { icon: require('cryptocurrency-icons/128/color/neo.png'), color: '#58BF00' , description: '', website: '' },
	"neos": { icon: require('cryptocurrency-icons/128/color/neos.png'), color: '#E5F300' , description: '', website: '' },
	"neu": { icon: require('cryptocurrency-icons/128/color/neu.png'), color: '#B3BA00' , description: '', website: '' },
	"nexo": { icon: require('cryptocurrency-icons/128/color/nexo.png'), color: '#1A4199' , description: '', website: '' },
	"ngc": { icon: require('cryptocurrency-icons/128/color/ngc.png'), color: '#F80000' , description: '', website: '' },
	"nio": { icon: require('cryptocurrency-icons/128/color/nio.png'), color: '#70C9C9' , description: '', website: '' },
	"nlc2": { icon: require('cryptocurrency-icons/128/color/nlc2.png'), color: '#F28F01' , description: '', website: '' },
	"nlg": { icon: require('cryptocurrency-icons/128/color/nlg.png'), color: '#2AB0FD' , description: '', website: '' },
	"nmc": { icon: require('cryptocurrency-icons/128/color/nmc.png'), color: '#186C9D' , description: '', website: '' },
	"nmr": { icon: require('cryptocurrency-icons/128/color/nmr.png'), color: '#000000' , description: 'Numeraire is an Ethereum token that powers Numerai, a San Francisco-based hedge fund that crowdsources artificial intelligence to make investments in major stock markets around the world. Numeraire (NMR) holders can stake their NMR tokens every week on specific predictions. Successful predictions are rewarded with more NMR.', website: 'https://numer.ai/' },
	"npxs": { icon: require('cryptocurrency-icons/128/color/npxs.png'), color: '#F5D100' , description: '', website: '' },
	"nu": { icon: require('./../../assets/cryptos/nu.png'), color: '#1D64FA' , description: 'NuCypher (NU) is an Ethereum token that can be staked to run a node on the NuCypher network. NuCypher describes itself as a threshold cryptography network that provides data privacy and key management for decentralized applications and protocols.', website: 'https://www.nucypher.com/' },
	"nuls": { icon: require('cryptocurrency-icons/128/color/nuls.png'), color: '#81BD39' , description: '', website: '' },
	"nxs": { icon: require('cryptocurrency-icons/128/color/nxs.png'), color: '#4099CD' , description: '', website: '' },
	"nxt": { icon: require('cryptocurrency-icons/128/color/nxt.png'), color: '#008FBB' , description: '', website: '' },
	"oax": { icon: require('cryptocurrency-icons/128/color/oax.png'), color: '#164B79' , description: '', website: '' },
	"ok": { icon: require('cryptocurrency-icons/128/color/ok.png'), color: '#000000' , description: '', website: '' },
	"omg": { icon: require('cryptocurrency-icons/128/color/omg.png'), color: '#101010' , description: 'The OMG Network (formerly OmiseGO) is a value transfer network for Ethereum and any ERC-20 token. It describes itself as the first production-grade layer-2 Ethereum scaling solution and aims to let people move money and a variety of digital values on the blockchain faster, cheaper, and without compromising on security.', website: 'https://omg.network/' },
	"omni": { icon: require('cryptocurrency-icons/128/color/omni.png'), color: '#1C347A' , description: '', website: '' },
	"ong": { icon: require('cryptocurrency-icons/128/color/ong.png'), color: '#000000' , description: '', website: '' },
	"ont": { icon: require('cryptocurrency-icons/128/color/ont.png'), color: '#32A4BE' , description: '', website: '' },
	"oot": { icon: require('cryptocurrency-icons/128/color/oot.png'), color: '#25AAE1' , description: '', website: '' },
	"ost": { icon: require('cryptocurrency-icons/128/color/ost.png'), color: '#34445B' , description: '', website: '' },
	"ox": { icon: require('cryptocurrency-icons/128/color/ox.png'), color: '#4392CD' , description: '', website: '' },
	"oxt": { icon: require('cryptocurrency-icons/128/color/oxt.png'), color: '#5E45BA' , description: 'Orchid (OXT) is an Ethereum token that powers the Orchid network, a peer-to-peer privacy tool that includes a decentralized VPN and other features designed to give users more control over their Internet connection. OXT can be used to pay for bandwidth or staked by bandwidth providers in order to operate a node.', website: 'https://www.orchid.com/' },
	"part": { icon: require('cryptocurrency-icons/128/color/part.png'), color: '#03E8B0' , description: '', website: '' },
	"pasc": { icon: require('cryptocurrency-icons/128/color/pasc.png'), color: '#F7931E' , description: '', website: '' },
	"pasl": { icon: require('cryptocurrency-icons/128/color/pasl.png'), color: '#00ACFF' , description: '', website: '' },
	"pax": { icon: require('cryptocurrency-icons/128/color/pax.png'), color: '#EDE708' , description: '', website: '' },
	"pay": { icon: require('cryptocurrency-icons/128/color/pay.png'), color: '#302C2C' , description: '', website: '' },
	"payx": { icon: require('cryptocurrency-icons/128/color/payx.png'), color: '#663300' , description: '', website: '' },
	"pink": { icon: require('cryptocurrency-icons/128/color/pink.png'), color: '#ED79AA' , description: '', website: '' },
	"pirl": { icon: require('cryptocurrency-icons/128/color/pirl.png'), color: '#96B73D' , description: '', website: '' },
	"pivx": { icon: require('cryptocurrency-icons/128/color/pivx.png'), color: '#5E4778' , description: '', website: '' },
	"plr": { icon: require('cryptocurrency-icons/128/color/plr.png'), color: '#00BFFF' , description: '', website: '' },
	"poa": { icon: require('cryptocurrency-icons/128/color/poa.png'), color: '#444FA1' , description: '', website: '' },
	"poe": { icon: require('cryptocurrency-icons/128/color/poe.png'), color: '#DCD6CC' , description: '', website: '' },
	"polis": { icon: require('cryptocurrency-icons/128/color/polis.png'), color: '#2C3E50' , description: '', website: '' },
	"poly": { icon: require('cryptocurrency-icons/128/color/poly.png'), color: '#4C5A95' , description: '', website: '' },
	"pot": { icon: require('cryptocurrency-icons/128/color/pot.png'), color: '#105B2F' , description: '', website: '' },
	"powr": { icon: require('cryptocurrency-icons/128/color/powr.png'), color: '#05BCA9' , description: '', website: '' },
	"ppc": { icon: require('cryptocurrency-icons/128/color/ppc.png'), color: '#3CB054' , description: '', website: '' },
	"ppp": { icon: require('cryptocurrency-icons/128/color/ppp.png'), color: '#348F8D' , description: '', website: '' },
	"ppt": { icon: require('cryptocurrency-icons/128/color/ppt.png'), color: '#152743' , description: '', website: '' },
	"pre": { icon: require('cryptocurrency-icons/128/color/pre.png'), color: '#3A8CBD' , description: '', website: '' },
	"prl": { icon: require('cryptocurrency-icons/128/color/prl.png'), color: '#1061E3' , description: '', website: '' },
	"pungo": { icon: require('cryptocurrency-icons/128/color/pungo.png'), color: '#22B573' , description: '', website: '' },
	"pura": { icon: require('cryptocurrency-icons/128/color/pura.png'), color: '#333333' , description: '', website: '' },
	"qash": { icon: require('cryptocurrency-icons/128/color/qash.png'), color: '#1347E8' , description: '', website: '' },
	"qiwi": { icon: require('cryptocurrency-icons/128/color/qiwi.png'), color: '#FF8C00' , description: '', website: '' },
	"qlc": { icon: require('cryptocurrency-icons/128/color/qlc.png'), color: '#610089' , description: '', website: '' },
	"qrl": { icon: require('cryptocurrency-icons/128/color/qrl.png'), color: '#252525' , description: '', website: '' },
	"qsp": { icon: require('cryptocurrency-icons/128/color/qsp.png'), color: '#454545' , description: '', website: '' },
	"qtum": { icon: require('cryptocurrency-icons/128/color/qtum.png'), color: '#2E9AD0' , description: '', website: '' },
	"r": { icon: require('cryptocurrency-icons/128/color/r.png'), color: '#771A4E' , description: '', website: '' },
	"rads": { icon: require('cryptocurrency-icons/128/color/rads.png'), color: '#9D4BEF' , description: '', website: '' },
	"rap": { icon: require('cryptocurrency-icons/128/color/rap.png'), color: '#000000' , description: '', website: '' },
	"rcn": { icon: require('cryptocurrency-icons/128/color/rcn.png'), color: '#3555F9' , description: '', website: '' },
	"rdd": { icon: require('cryptocurrency-icons/128/color/rdd.png'), color: '#E30613' , description: '', website: '' },
	"rdn": { icon: require('cryptocurrency-icons/128/color/rdn.png'), color: '#2A2A2A' , description: '', website: '' },
	"ren": { icon: require('cryptocurrency-icons/128/color/ren.png'), color: '#001E3D' , description: 'Ren (REN) is an Ethereum token that powers Ren’s open protocol for transferring cryptocurrencies between blockchains. Ren aims to bring popular assets like Bitcoin and Zcash to blockchains including Ethereum, making it possible for these assets to participate in a multi-chain decentralized finance ecosystem.', website: 'https://renproject.io/' },
	"rep": { icon: require('cryptocurrency-icons/128/color/rep.png'), color: '#612A52' , description: 'Augur’s Reputation token (REP) is an Ethereum token designed for reporting and disputing the outcome of events on online prediction markets. Reporters are rewarded for reporting the outcome of events correctly.', website: 'https://www.augur.net/' },
	"repv2": { icon: require('cryptocurrency-icons/128/color/repv2.png'), color: '#0E0E21' , description: '', website: '' },
	"req": { icon: require('cryptocurrency-icons/128/color/req.png'), color: '#00E6A0' , description: '', website: '' },
	"rhoc": { icon: require('cryptocurrency-icons/128/color/rhoc.png'), color: '#CC1E46' , description: '', website: '' },
	"ric": { icon: require('cryptocurrency-icons/128/color/ric.png'), color: '#61E4DE' , description: '', website: '' },
	"rise": { icon: require('cryptocurrency-icons/128/color/rise.png'), color: '#F49352' , description: '', website: '' },
	"rlc": { icon: require('cryptocurrency-icons/128/color/rlc.png'), color: '#FFD800' , description: '', website: '' },
	"rpx": { icon: require('cryptocurrency-icons/128/color/rpx.png'), color: '#8D181B' , description: '', website: '' },
	"rub": { icon: require('cryptocurrency-icons/128/color/rub.png'), color: '#65D1FF' , description: '', website: '' },
	"rvn": { icon: require('cryptocurrency-icons/128/color/rvn.png'), color: '#384182' , description: '', website: '' },
	"ryo": { icon: require('cryptocurrency-icons/128/color/ryo.png'), color: '#3D58B0' , description: '', website: '' },
	"safe": { icon: require('cryptocurrency-icons/128/color/safe.png'), color: '#00688D' , description: '', website: '' },
	"sai": { icon: require('cryptocurrency-icons/128/color/sai.png'), color: '#B68900' , description: '', website: '' },
	"salt": { icon: require('cryptocurrency-icons/128/color/salt.png'), color: '#1BEEF4' , description: '', website: '' },
	"san": { icon: require('cryptocurrency-icons/128/color/san.png'), color: '#2B77B3' , description: '', website: '' },
	"sbd": { icon: require('cryptocurrency-icons/128/color/sbd.png'), color: '#56A8F3' , description: '', website: '' },
	"sberbank": { icon: require('cryptocurrency-icons/128/color/sberbank.png'), color: '#48B254' , description: '', website: '' },
	"sc": { icon: require('cryptocurrency-icons/128/color/sc.png'), color: '#20EE82' , description: '', website: '' },
	"shift": { icon: require('cryptocurrency-icons/128/color/shift.png'), color: '#964B9C' , description: '', website: '' },
	"sib": { icon: require('cryptocurrency-icons/128/color/sib.png'), color: '#057BC1' , description: '', website: '' },
	"sin": { icon: require('cryptocurrency-icons/128/color/sin.png'), color: '#F5342E' , description: '', website: '' },
	"sky": { icon: require('cryptocurrency-icons/128/color/sky.png'), color: '#0072FF' , description: '', website: '' },
	"slr": { icon: require('cryptocurrency-icons/128/color/slr.png'), color: '#FDA616' , description: '', website: '' },
	"sls": { icon: require('cryptocurrency-icons/128/color/sls.png'), color: '#8E9495' , description: '', website: '' },
	"smart": { icon: require('cryptocurrency-icons/128/color/smart.png'), color: '#FEC60D' , description: '', website: '' },
	"sngls": { icon: require('cryptocurrency-icons/128/color/sngls.png'), color: '#B30D23' , description: '', website: '' },
	"snm": { icon: require('cryptocurrency-icons/128/color/snm.png'), color: '#0B1C26' , description: '', website: '' },
	"snt": { icon: require('cryptocurrency-icons/128/color/snt.png'), color: '#5B6DEE' , description: '', website: '' },
	"snx": { icon: require('./../../assets/cryptos/snx.png'), color: '#090220' , description: 'Synthetix Network Token(SNX) is an Ethereum token that powers Synthetix, a decentralised synthetic asset issuance protocol. Synthetic assets are minted when token holders stake their SNX as collateral using Mintr, a decentralised application for interacting with the Synthetix contracts. The protocol currently supports synthetic fiat currencies, cryptocurrencies, and commodities.', website: 'https://www.synthetix.io/' },
	"soc": { icon: require('cryptocurrency-icons/128/color/soc.png'), color: '#199248' , description: '', website: '' },
	"spank": { icon: require('cryptocurrency-icons/128/color/spank.png'), color: '#FF3B81' , description: '', website: '' },
	"sphtx": { icon: require('cryptocurrency-icons/128/color/sphtx.png'), color: '#2CBEAA' , description: '', website: '' },
	"srn": { icon: require('cryptocurrency-icons/128/color/srn.png'), color: '#1C1C1C' , description: '', website: '' },
	"stak": { icon: require('cryptocurrency-icons/128/color/stak.png'), color: '#F2941B' , description: '', website: '' },
	"start": { icon: require('cryptocurrency-icons/128/color/start.png'), color: '#01AEF0' , description: '', website: '' },
	"steem": { icon: require('cryptocurrency-icons/128/color/steem.png'), color: '#4BA2F2' , description: '', website: '' },
	"storj": { icon: require('cryptocurrency-icons/128/color/storj.png'), color: '#2683FF' , description: '', website: '' },
	"storm": { icon: require('cryptocurrency-icons/128/color/storm.png'), color: '#080D98' , description: '', website: '' },
	"stq": { icon: require('cryptocurrency-icons/128/color/stq.png'), color: '#2EC4E7' , description: '', website: '' },
	"strat": { icon: require('cryptocurrency-icons/128/color/strat.png'), color: '#1387C9' , description: '', website: '' },
	"stx": { icon: require('cryptocurrency-icons/128/color/stx.png'), color: '#7324F0' , description: '', website: '' },
	"sub": { icon: require('cryptocurrency-icons/128/color/sub.png'), color: '#E53431' , description: '', website: '' },
	"sumo": { icon: require('cryptocurrency-icons/128/color/sumo.png'), color: '#2D9CDB' , description: '', website: '' },
	"sys": { icon: require('cryptocurrency-icons/128/color/sys.png'), color: '#0082C6' , description: '', website: '' },
	"taas": { icon: require('cryptocurrency-icons/128/color/taas.png'), color: '#002342' , description: '', website: '' },
	"tau": { icon: require('cryptocurrency-icons/128/color/tau.png'), color: '#7B346E' , description: '', website: '' },
	"tbx": { icon: require('cryptocurrency-icons/128/color/tbx.png'), color: '#5244D4' , description: '', website: '' },
	"tel": { icon: require('cryptocurrency-icons/128/color/tel.png'), color: '#14C8FF' , description: '', website: '' },
	"ten": { icon: require('cryptocurrency-icons/128/color/ten.png'), color: '#0899CD' , description: '', website: '' },
	"tern": { icon: require('cryptocurrency-icons/128/color/tern.png'), color: '#F4C257' , description: '', website: '' },
	"tgch": { icon: require('cryptocurrency-icons/128/color/tgch.png'), color: '#434247' , description: '', website: '' },
	"theta": { icon: require('cryptocurrency-icons/128/color/theta.png'), color: '#2AB8E6' , description: '', website: '' },
	"tix": { icon: require('cryptocurrency-icons/128/color/tix.png'), color: '#EF494D' , description: '', website: '' },
	"tkn": { icon: require('cryptocurrency-icons/128/color/tkn.png'), color: '#24DD7B' , description: '', website: '' },
	"tks": { icon: require('cryptocurrency-icons/128/color/tks.png'), color: '#895AF8' , description: '', website: '' },
	"tnb": { icon: require('cryptocurrency-icons/128/color/tnb.png'), color: '#FFC04E' , description: '', website: '' },
	"tnc": { icon: require('cryptocurrency-icons/128/color/tnc.png'), color: '#FF439B' , description: '', website: '' },
	"tnt": { icon: require('cryptocurrency-icons/128/color/tnt.png'), color: '#FF4081' , description: '', website: '' },
	"tomo": { icon: require('cryptocurrency-icons/128/color/tomo.png'), color: '#1A1F36' , description: '', website: '' },
	"tpay": { icon: require('cryptocurrency-icons/128/color/tpay.png'), color: '#3058A6' , description: '', website: '' },
	"trig": { icon: require('cryptocurrency-icons/128/color/trig.png'), color: '#30C0F2' , description: '', website: '' },
	"trtl": { icon: require('cryptocurrency-icons/128/color/trtl.png'), color: '#00843D' , description: '', website: '' },
	"trx": { icon: require('cryptocurrency-icons/128/color/trx.png'), color: '#EF0027' , description: '', website: '' },
	"tusd": { icon: require('cryptocurrency-icons/128/color/tusd.png'), color: '#2B2E7F' , description: '', website: '' },
	"tzc": { icon: require('cryptocurrency-icons/128/color/tzc.png'), color: '#374851' , description: '', website: '' },
	"ubq": { icon: require('cryptocurrency-icons/128/color/ubq.png'), color: '#00EB8F' , description: '', website: '' },
	"uma": { icon: require('cryptocurrency-icons/128/color/uma.png'), color: '#FF4A49' , description: 'UMA is an Ethereum token that describes itself as “an open-source protocol that allows developers to design and create their own financial contracts and synthetic assets.” The protocol’s name comes from the team’s goal of creating universal market access (UMA).', website: 'https://umaproject.org/' },
	"uni": { icon: require('cryptocurrency-icons/128/color/uni.png'), color: '#FF007A' , description: 'Uniswap (UNI) is an Ethereum token that powers Uniswap, an automated liquidity provider that’s designed to make it easy to exchange Ethereum (ERC-20) tokens. There is no orderbook or central facilitator on Uniswap. Instead, tokens are exchanged through liquidity pools that are defined by smart contracts.', website: 'https://uniswap.org/' },
	"unity": { icon: require('cryptocurrency-icons/128/color/unity.png'), color: '#F58634' , description: '', website: '' },
	"usd": { icon: require('cryptocurrency-icons/128/color/usd.png'), color: '#6BDE07' , description: '', website: '' },
	"usdc": { icon: require('cryptocurrency-icons/128/color/usdc.png'), color: '#2775C9' , description: 'USD Coin (USDC) is a stablecoin fully backed by the US dollar and developed by the CENTRE consortium. Coinbase customers with US dollar accounts may exchange 1 USDC for US$1.00 (and vice versa) on Coinbase in jurisdictions where USDC support is available. The graph above reflects USDC’s current and historical redemption value of US$1.00, which may not match the price of USDC on other exchanges. USDC is an Ethereum token and is the only fiat-backed stablecoin currently supported by Coinbase. Note: Coinbase only supports USDC running on Ethereum (ERC-20).', website: 'https://www.coinbase.com/usdc/' },
	"usdt": { icon: require('cryptocurrency-icons/128/color/usdt.png'), color: '#27A17C' , description: '', website: '' },
	"utk": { icon: require('cryptocurrency-icons/128/color/utk.png'), color: '#30367A' , description: '', website: '' },
	"veri": { icon: require('cryptocurrency-icons/128/color/veri.png'), color: '#FF9933' , description: '', website: '' },
	"vet": { icon: require('cryptocurrency-icons/128/color/vet.png'), color: '#15BDFF' , description: '', website: '' },
	"via": { icon: require('cryptocurrency-icons/128/color/via.png'), color: '#565656' , description: '', website: '' },
	"vib": { icon: require('cryptocurrency-icons/128/color/vib.png'), color: '#FF1F43' , description: '', website: '' },
	"vibe": { icon: require('cryptocurrency-icons/128/color/vibe.png'), color: '#338BE5' , description: '', website: '' },
	"vivo": { icon: require('cryptocurrency-icons/128/color/vivo.png'), color: '#408AF1' , description: '', website: '' },
	"vrc": { icon: require('cryptocurrency-icons/128/color/vrc.png'), color: '#418BCA' , description: '', website: '' },
	"vrsc": { icon: require('cryptocurrency-icons/128/color/vrsc.png'), color: '#FFB500' , description: '', website: '' },
	"vtc": { icon: require('cryptocurrency-icons/128/color/vtc.png'), color: '#048657' , description: '', website: '' },
	"vtho": { icon: require('cryptocurrency-icons/128/color/vtho.png'), color: '#2A5284' , description: '', website: '' },
	"wabi": { icon: require('cryptocurrency-icons/128/color/wabi.png'), color: '#3A9B32' , description: '', website: '' },
	"wan": { icon: require('cryptocurrency-icons/128/color/wan.png'), color: '#136AAD' , description: '', website: '' },
	"waves": { icon: require('cryptocurrency-icons/128/color/waves.png'), color: '#0155FF' , description: '', website: '' },
	"wax": { icon: require('cryptocurrency-icons/128/color/wax.png'), color: '#F89022' , description: '', website: '' },
	"wbtc": { icon: require('cryptocurrency-icons/128/color/wbtc.png'), color: '#1F1B2C' , description: 'Wrapped Bitcoin (WBTC) is an Ethereum token that is intended to represent Bitcoin (BTC) on the Ethereum blockchain. It is not Bitcoin, but rather a separate ERC-20 token that’s designed to track Bitcoin’s value. WBTC was created to allow Bitcoin holders to participate in decentralized finance (“DeFi”) apps that are popular on Ethereum. Through a WBTC partner, 1 Bitcoin can be exchanged for 1 Wrapped Bitcoin, and vice-versa. The BTC that backs WBTC is verifiable through a “proof of reserve” system that verifies the 1:1 backing between minted WBTC tokens and Bitcoin stored by custodians. WBTC is maintained by a group called the WBTC DAO that consists of over 30 members. It was originally started by BitGo, Ren, and Kyber.', website: 'https://wbtc.network/' },
	"wgr": { icon: require('cryptocurrency-icons/128/color/wgr.png'), color: '#B80000' , description: '', website: '' },
	"wicc": { icon: require('cryptocurrency-icons/128/color/wicc.png'), color: '#5783CB' , description: '', website: '' },
	"wings": { icon: require('cryptocurrency-icons/128/color/wings.png'), color: '#0DC9F7' , description: '', website: '' },
	"wpr": { icon: require('cryptocurrency-icons/128/color/wpr.png'), color: '#FFE600' , description: '', website: '' },
	"wtc": { icon: require('cryptocurrency-icons/128/color/wtc.png'), color: '#8200FF' , description: '', website: '' },
	"x": { icon: require('cryptocurrency-icons/128/color/x.png'), color: '#3B5999' , description: '', website: '' },
	"xas": { icon: require('cryptocurrency-icons/128/color/xas.png'), color: '#FAA00D' , description: '', website: '' },
	"xbc": { icon: require('cryptocurrency-icons/128/color/xbc.png'), color: '#F7931A' , description: '', website: '' },
	"xbp": { icon: require('cryptocurrency-icons/128/color/xbp.png'), color: '#21AF67' , description: '', website: '' },
	"xby": { icon: require('cryptocurrency-icons/128/color/xby.png'), color: '#56F4F1' , description: '', website: '' },
	"xcp": { icon: require('cryptocurrency-icons/128/color/xcp.png'), color: '#ED1650' , description: '', website: '' },
	"xdn": { icon: require('cryptocurrency-icons/128/color/xdn.png'), color: '#4F7BA2' , description: '', website: '' },
	"xem": { icon: require('cryptocurrency-icons/128/color/xem.png'), color: '#67B2E8' , description: '', website: '' },
	"xin": { icon: require('cryptocurrency-icons/128/color/xin.png'), color: '#1EB5FA' , description: '', website: '' },
	"xlm": { icon: require('cryptocurrency-icons/128/color/xlm.png'), color: '#000000' , description: 'Stellar’s cryptocurrency, the Stellar Lumen (XLM), powers the Stellar payment network. Stellar aims to connect banks, payment systems, and individuals quickly and reliably.', website: 'https://www.stellar.org/' },
	"xmcc": { icon: require('cryptocurrency-icons/128/color/xmcc.png'), color: '#DD0632' , description: '', website: '' },
	"xmg": { icon: require('cryptocurrency-icons/128/color/xmg.png'), color: '#004A80' , description: '', website: '' },
	"xmo": { icon: require('cryptocurrency-icons/128/color/xmo.png'), color: '#FF6600' , description: '', website: '' },
	"xmr": { icon: require('cryptocurrency-icons/128/color/xmr.png'), color: '#FF6600' , description: '', website: '' },
	"xmy": { icon: require('cryptocurrency-icons/128/color/xmy.png'), color: '#EC0F76' , description: '', website: '' },
	"xp": { icon: require('cryptocurrency-icons/128/color/xp.png'), color: '#008200' , description: '', website: '' },
	"xpa": { icon: require('cryptocurrency-icons/128/color/xpa.png'), color: '#4FA784' , description: '', website: '' },
	"xpm": { icon: require('cryptocurrency-icons/128/color/xpm.png'), color: '#FFD81B' , description: '', website: '' },
	"xrp": { icon: require('cryptocurrency-icons/128/color/xrp.png'), color: '#24292F' , description: 'In light of the SEC’s action against Ripple Labs, Inc., trading in XRP has been suspended as of January 19, 2021. XRP is the cryptocurrency used by the Ripple payment network. Built for enterprise use, XRP aims to be a fast, cost-efficient cryptocurrency for cross-border payments.', website: 'https://ripple.com/xrp/' },
	"xsg": { icon: require('cryptocurrency-icons/128/color/xsg.png'), color: '#D21E2B' , description: '', website: '' },
	"xtz": { icon: require('cryptocurrency-icons/128/color/xtz.png'), color: '#A6E000' , description: 'Tezos is a cryptocurrency and decentralized computing platform. Its features include proof of stake consensus, formal verification (which lets developers verify the correctness of their code), and the ability to let stakeholders vote on changes to the protocol. Tezos\'s block creation process is called "baking" — Tezos holders who stake their tokens can receive Tezos tokens as a reward for creating and verifying blocks.', website: 'https://www.tezos.com/' },
	"xuc": { icon: require('cryptocurrency-icons/128/color/xuc.png'), color: '#25AAE3' , description: '', website: '' },
	"xvc": { icon: require('cryptocurrency-icons/128/color/xvc.png'), color: '#B50126' , description: '', website: '' },
	"xvg": { icon: require('cryptocurrency-icons/128/color/xvg.png'), color: '#00CBFF' , description: '', website: '' },
	"xzc": { icon: require('cryptocurrency-icons/128/color/xzc.png'), color: '#23B852' , description: '', website: '' },
	"yfi": { icon: require('cryptocurrency-icons/128/color/yfi.png'), color: '#006AE2' , description: 'Yearn.finance (YFI) is an Ethereum token that governs the Yearn.finance platform. The platform is a yield optimizer that moves funds around the decentralized finance (“defi”) ecosystem in an effort to generate a high return.', website: 'https://yearn.finance/' },
	"yoyow": { icon: require('cryptocurrency-icons/128/color/yoyow.png'), color: '#21A5DE' , description: '', website: '' },
	"zcl": { icon: require('cryptocurrency-icons/128/color/zcl.png'), color: '#C87035' , description: '', website: '' },
	"zec": { icon: require('cryptocurrency-icons/128/color/zec.png'), color: '#ECB244' , description: 'Zcash is a cryptocurrency that offers two types of addresses: transparent addresses that are publicly visible on the Zcash blockchain and shielded addresses that are more private. Coinbase customers can receive Zcash from both transparent and shielded addresses and send Zcash to transparent addresses. Sending to shielded addresses is not supported at this time.', website: 'https://z.cash/' },
	"zel": { icon: require('cryptocurrency-icons/128/color/zel.png'), color: '#183C87' , description: '', website: '' },
	"zen": { icon: require('cryptocurrency-icons/128/color/zen.png'), color: '#00EAAB' , description: '', website: '' },
	"zest": { icon: require('cryptocurrency-icons/128/color/zest.png'), color: '#07BC9C' , description: '', website: '' },
	"zil": { icon: require('cryptocurrency-icons/128/color/zil.png'), color: '#49C1BF' , description: '', website: '' },
	"zilla": { icon: require('cryptocurrency-icons/128/color/zilla.png'), color: '#00004D' , description: '', website: '' },
	"zrx": { icon: require('cryptocurrency-icons/128/color/zrx.png'), color: '#302C2B' , description: 'ZRX is an Ethereum token that is used to power the 0x protocol. The protocol itself is designed to allow Ethereum tokens to be traded at a low cost directly from your wallet.', website: 'https://0x.org/' },
}

export default CryptoCurrenciesIconMap;